// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: analytics.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const castPollVote = `-- name: CastPollVote :one
INSERT INTO poll_votes (
    poll_id, voter_id, vote
) VALUES (
    $1, $2, $3
)
ON CONFLICT (poll_id, voter_id) DO UPDATE SET vote = EXCLUDED.vote
RETURNING id, poll_id, voter_id, vote, created_at
`

type CastPollVoteParams struct {
	PollID  pgtype.UUID   `db:"poll_id" json:"poll_id"`
	VoterID pgtype.UUID   `db:"voter_id" json:"voter_id"`
	Vote    PollVoteValue `db:"vote" json:"vote"`
}

func (q *Queries) CastPollVote(ctx context.Context, arg CastPollVoteParams) (PollVote, error) {
	row := q.db.QueryRow(ctx, castPollVote, arg.PollID, arg.VoterID, arg.Vote)
	var i PollVote
	err := row.Scan(
		&i.ID,
		&i.PollID,
		&i.VoterID,
		&i.Vote,
		&i.CreatedAt,
	)
	return i, err
}

const checkVoteExists = `-- name: CheckVoteExists :one
SELECT EXISTS(
    SELECT 1 FROM poll_votes
    WHERE poll_id = $1 AND voter_id = $2
) as vote_exists
`

type CheckVoteExistsParams struct {
	PollID  pgtype.UUID `db:"poll_id" json:"poll_id"`
	VoterID pgtype.UUID `db:"voter_id" json:"voter_id"`
}

func (q *Queries) CheckVoteExists(ctx context.Context, arg CheckVoteExistsParams) (bool, error) {
	row := q.db.QueryRow(ctx, checkVoteExists, arg.PollID, arg.VoterID)
	var vote_exists bool
	err := row.Scan(&vote_exists)
	return vote_exists, err
}

const countPollVotesByPoll = `-- name: CountPollVotesByPoll :one
SELECT COUNT(*) FROM poll_votes
WHERE poll_id = $1
  AND ($2::text IS NULL OR vote = $2)
`

type CountPollVotesByPollParams struct {
	PollID  pgtype.UUID `db:"poll_id" json:"poll_id"`
	Column2 string      `db:"column_2" json:"column_2"`
}

func (q *Queries) CountPollVotesByPoll(ctx context.Context, arg CountPollVotesByPollParams) (int64, error) {
	row := q.db.QueryRow(ctx, countPollVotesByPoll, arg.PollID, arg.Column2)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createPoll = `-- name: CreatePoll :one

INSERT INTO polls (
    bootcamp_id, problem_id, question, created_by
) VALUES (
    $1, $2, $3, $4
)
RETURNING id, bootcamp_id, problem_id, question, created_by, created_at
`

type CreatePollParams struct {
	BootcampID pgtype.UUID `db:"bootcamp_id" json:"bootcamp_id"`
	ProblemID  pgtype.UUID `db:"problem_id" json:"problem_id"`
	Question   string      `db:"question" json:"question"`
	CreatedBy  pgtype.UUID `db:"created_by" json:"created_by"`
}

// Polls
func (q *Queries) CreatePoll(ctx context.Context, arg CreatePollParams) (Poll, error) {
	row := q.db.QueryRow(ctx, createPoll,
		arg.BootcampID,
		arg.ProblemID,
		arg.Question,
		arg.CreatedBy,
	)
	var i Poll
	err := row.Scan(
		&i.ID,
		&i.BootcampID,
		&i.ProblemID,
		&i.Question,
		&i.CreatedBy,
		&i.CreatedAt,
	)
	return i, err
}

const getLeaderboardByBootcamp = `-- name: GetLeaderboardByBootcamp :many
SELECT le.id, le.bootcamp_id, le.bootcamp_enrollment_id, le.problems_completed, le.problems_attempted, le.completion_rate, le.streak_days, le.score, le.rank, le.calculated_at, u.name, u.avatar_url
FROM leaderboard_entries le
JOIN bootcamp_enrollments be ON le.bootcamp_enrollment_id = be.id
JOIN organization_members om ON be.organization_member_id = om.id
JOIN users u ON om.user_id = u.id
WHERE le.bootcamp_id = $1
ORDER BY le.rank ASC
`

type GetLeaderboardByBootcampRow struct {
	ID                   pgtype.UUID        `db:"id" json:"id"`
	BootcampID           pgtype.UUID        `db:"bootcamp_id" json:"bootcamp_id"`
	BootcampEnrollmentID pgtype.UUID        `db:"bootcamp_enrollment_id" json:"bootcamp_enrollment_id"`
	ProblemsCompleted    int32              `db:"problems_completed" json:"problems_completed"`
	ProblemsAttempted    int32              `db:"problems_attempted" json:"problems_attempted"`
	CompletionRate       float32            `db:"completion_rate" json:"completion_rate"`
	StreakDays           int32              `db:"streak_days" json:"streak_days"`
	Score                int32              `db:"score" json:"score"`
	Rank                 int32              `db:"rank" json:"rank"`
	CalculatedAt         pgtype.Timestamptz `db:"calculated_at" json:"calculated_at"`
	Name                 string             `db:"name" json:"name"`
	AvatarUrl            pgtype.Text        `db:"avatar_url" json:"avatar_url"`
}

func (q *Queries) GetLeaderboardByBootcamp(ctx context.Context, bootcampID pgtype.UUID) ([]GetLeaderboardByBootcampRow, error) {
	rows, err := q.db.Query(ctx, getLeaderboardByBootcamp, bootcampID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetLeaderboardByBootcampRow{}
	for rows.Next() {
		var i GetLeaderboardByBootcampRow
		if err := rows.Scan(
			&i.ID,
			&i.BootcampID,
			&i.BootcampEnrollmentID,
			&i.ProblemsCompleted,
			&i.ProblemsAttempted,
			&i.CompletionRate,
			&i.StreakDays,
			&i.Score,
			&i.Rank,
			&i.CalculatedAt,
			&i.Name,
			&i.AvatarUrl,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getPoll = `-- name: GetPoll :one
SELECT id, bootcamp_id, problem_id, question, created_by, created_at FROM polls
WHERE id = $1 LIMIT 1
`

func (q *Queries) GetPoll(ctx context.Context, id pgtype.UUID) (Poll, error) {
	row := q.db.QueryRow(ctx, getPoll, id)
	var i Poll
	err := row.Scan(
		&i.ID,
		&i.BootcampID,
		&i.ProblemID,
		&i.Question,
		&i.CreatedBy,
		&i.CreatedAt,
	)
	return i, err
}

const getPollResults = `-- name: GetPollResults :many
SELECT vote, COUNT(*) as vote_count
FROM poll_votes
WHERE poll_id = $1
GROUP BY vote
`

type GetPollResultsRow struct {
	Vote      PollVoteValue `db:"vote" json:"vote"`
	VoteCount int64         `db:"vote_count" json:"vote_count"`
}

func (q *Queries) GetPollResults(ctx context.Context, pollID pgtype.UUID) ([]GetPollResultsRow, error) {
	rows, err := q.db.Query(ctx, getPollResults, pollID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetPollResultsRow{}
	for rows.Next() {
		var i GetPollResultsRow
		if err := rows.Scan(&i.Vote, &i.VoteCount); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getUserVoteForPoll = `-- name: GetUserVoteForPoll :one
SELECT id, poll_id, voter_id, vote, created_at FROM poll_votes
WHERE poll_id = $1 AND voter_id = $2
LIMIT 1
`

type GetUserVoteForPollParams struct {
	PollID  pgtype.UUID `db:"poll_id" json:"poll_id"`
	VoterID pgtype.UUID `db:"voter_id" json:"voter_id"`
}

func (q *Queries) GetUserVoteForPoll(ctx context.Context, arg GetUserVoteForPollParams) (PollVote, error) {
	row := q.db.QueryRow(ctx, getUserVoteForPoll, arg.PollID, arg.VoterID)
	var i PollVote
	err := row.Scan(
		&i.ID,
		&i.PollID,
		&i.VoterID,
		&i.Vote,
		&i.CreatedAt,
	)
	return i, err
}

const listPollVotesByPoll = `-- name: ListPollVotesByPoll :many
SELECT pv.id, pv.poll_id, pv.voter_id, pv.vote, pv.created_at, u.name as voter_name
FROM poll_votes pv
JOIN bootcamp_enrollments be ON pv.voter_id = be.id
JOIN organization_members om ON be.organization_member_id = om.id
JOIN users u ON om.user_id = u.id
WHERE pv.poll_id = $1
  AND ($2::text IS NULL OR pv.vote = $2)
ORDER BY pv.created_at DESC
LIMIT $3 OFFSET $4
`

type ListPollVotesByPollParams struct {
	PollID  pgtype.UUID `db:"poll_id" json:"poll_id"`
	Column2 string      `db:"column_2" json:"column_2"`
	Limit   int32       `db:"limit" json:"limit"`
	Offset  int32       `db:"offset" json:"offset"`
}

type ListPollVotesByPollRow struct {
	ID        pgtype.UUID        `db:"id" json:"id"`
	PollID    pgtype.UUID        `db:"poll_id" json:"poll_id"`
	VoterID   pgtype.UUID        `db:"voter_id" json:"voter_id"`
	Vote      PollVoteValue      `db:"vote" json:"vote"`
	CreatedAt pgtype.Timestamptz `db:"created_at" json:"created_at"`
	VoterName string             `db:"voter_name" json:"voter_name"`
}

func (q *Queries) ListPollVotesByPoll(ctx context.Context, arg ListPollVotesByPollParams) ([]ListPollVotesByPollRow, error) {
	rows, err := q.db.Query(ctx, listPollVotesByPoll,
		arg.PollID,
		arg.Column2,
		arg.Limit,
		arg.Offset,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListPollVotesByPollRow{}
	for rows.Next() {
		var i ListPollVotesByPollRow
		if err := rows.Scan(
			&i.ID,
			&i.PollID,
			&i.VoterID,
			&i.Vote,
			&i.CreatedAt,
			&i.VoterName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPollsByBootcamp = `-- name: ListPollsByBootcamp :many
SELECT p.id, p.bootcamp_id, p.problem_id, p.question, p.created_by, p.created_at, prob.title as problem_title
FROM polls p
JOIN problems prob ON p.problem_id = prob.id
WHERE p.bootcamp_id = $1
ORDER BY p.created_at DESC
`

type ListPollsByBootcampRow struct {
	ID           pgtype.UUID        `db:"id" json:"id"`
	BootcampID   pgtype.UUID        `db:"bootcamp_id" json:"bootcamp_id"`
	ProblemID    pgtype.UUID        `db:"problem_id" json:"problem_id"`
	Question     string             `db:"question" json:"question"`
	CreatedBy    pgtype.UUID        `db:"created_by" json:"created_by"`
	CreatedAt    pgtype.Timestamptz `db:"created_at" json:"created_at"`
	ProblemTitle string             `db:"problem_title" json:"problem_title"`
}

func (q *Queries) ListPollsByBootcamp(ctx context.Context, bootcampID pgtype.UUID) ([]ListPollsByBootcampRow, error) {
	rows, err := q.db.Query(ctx, listPollsByBootcamp, bootcampID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListPollsByBootcampRow{}
	for rows.Next() {
		var i ListPollsByBootcampRow
		if err := rows.Scan(
			&i.ID,
			&i.BootcampID,
			&i.ProblemID,
			&i.Question,
			&i.CreatedBy,
			&i.CreatedAt,
			&i.ProblemTitle,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const upsertLeaderboardEntry = `-- name: UpsertLeaderboardEntry :one
INSERT INTO leaderboard_entries (
    bootcamp_id, bootcamp_enrollment_id, problems_completed, problems_attempted, 
    completion_rate, streak_days, score, rank, calculated_at
) VALUES (
    $1, $2, $3, $4, $5, $6, $7, $8, CURRENT_TIMESTAMP
)
ON CONFLICT (bootcamp_id, bootcamp_enrollment_id) DO UPDATE SET
    problems_completed = EXCLUDED.problems_completed,
    problems_attempted = EXCLUDED.problems_attempted,
    completion_rate = EXCLUDED.completion_rate,
    streak_days = EXCLUDED.streak_days,
    score = EXCLUDED.score,
    rank = EXCLUDED.rank,
    calculated_at = CURRENT_TIMESTAMP
RETURNING id, bootcamp_id, bootcamp_enrollment_id, problems_completed, problems_attempted, completion_rate, streak_days, score, rank, calculated_at
`

type UpsertLeaderboardEntryParams struct {
	BootcampID           pgtype.UUID `db:"bootcamp_id" json:"bootcamp_id"`
	BootcampEnrollmentID pgtype.UUID `db:"bootcamp_enrollment_id" json:"bootcamp_enrollment_id"`
	ProblemsCompleted    int32       `db:"problems_completed" json:"problems_completed"`
	ProblemsAttempted    int32       `db:"problems_attempted" json:"problems_attempted"`
	CompletionRate       float32     `db:"completion_rate" json:"completion_rate"`
	StreakDays           int32       `db:"streak_days" json:"streak_days"`
	Score                int32       `db:"score" json:"score"`
	Rank                 int32       `db:"rank" json:"rank"`
}

func (q *Queries) UpsertLeaderboardEntry(ctx context.Context, arg UpsertLeaderboardEntryParams) (LeaderboardEntry, error) {
	row := q.db.QueryRow(ctx, upsertLeaderboardEntry,
		arg.BootcampID,
		arg.BootcampEnrollmentID,
		arg.ProblemsCompleted,
		arg.ProblemsAttempted,
		arg.CompletionRate,
		arg.StreakDays,
		arg.Score,
		arg.Rank,
	)
	var i LeaderboardEntry
	err := row.Scan(
		&i.ID,
		&i.BootcampID,
		&i.BootcampEnrollmentID,
		&i.ProblemsCompleted,
		&i.ProblemsAttempted,
		&i.CompletionRate,
		&i.StreakDays,
		&i.Score,
		&i.Rank,
		&i.CalculatedAt,
	)
	return i, err
}
