// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: assignment.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const addProblemToAssignmentGroup = `-- name: AddProblemToAssignmentGroup :exec
INSERT INTO assignment_group_problems (
    assignment_group_id, problem_id, position
) VALUES (
    $1, $2, $3
)
ON CONFLICT (assignment_group_id, problem_id) DO UPDATE SET position = EXCLUDED.position
`

type AddProblemToAssignmentGroupParams struct {
	AssignmentGroupID pgtype.UUID `db:"assignment_group_id" json:"assignment_group_id"`
	ProblemID         pgtype.UUID `db:"problem_id" json:"problem_id"`
	Position          pgtype.Int4 `db:"position" json:"position"`
}

func (q *Queries) AddProblemToAssignmentGroup(ctx context.Context, arg AddProblemToAssignmentGroupParams) error {
	_, err := q.db.Exec(ctx, addProblemToAssignmentGroup, arg.AssignmentGroupID, arg.ProblemID, arg.Position)
	return err
}

const archiveAssignment = `-- name: ArchiveAssignment :exec
UPDATE assignments
SET archived_at = CURRENT_TIMESTAMP
WHERE id = $1
`

func (q *Queries) ArchiveAssignment(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, archiveAssignment, id)
	return err
}

const assignGroupToMentee = `-- name: AssignGroupToMentee :one

INSERT INTO assignments (
    assignment_group_id, bootcamp_enrollment_id, assigned_by, deadline_at, status
) VALUES (
    $1, $2, $3, $4, $5
)
RETURNING id, assignment_group_id, bootcamp_enrollment_id, assigned_by, assigned_at, deadline_at, status, archived_at, created_at, updated_at
`

type AssignGroupToMenteeParams struct {
	AssignmentGroupID    pgtype.UUID        `db:"assignment_group_id" json:"assignment_group_id"`
	BootcampEnrollmentID pgtype.UUID        `db:"bootcamp_enrollment_id" json:"bootcamp_enrollment_id"`
	AssignedBy           pgtype.UUID        `db:"assigned_by" json:"assigned_by"`
	DeadlineAt           pgtype.Timestamptz `db:"deadline_at" json:"deadline_at"`
	Status               AssignmentStatus   `db:"status" json:"status"`
}

// Assignment Instances
func (q *Queries) AssignGroupToMentee(ctx context.Context, arg AssignGroupToMenteeParams) (Assignment, error) {
	row := q.db.QueryRow(ctx, assignGroupToMentee,
		arg.AssignmentGroupID,
		arg.BootcampEnrollmentID,
		arg.AssignedBy,
		arg.DeadlineAt,
		arg.Status,
	)
	var i Assignment
	err := row.Scan(
		&i.ID,
		&i.AssignmentGroupID,
		&i.BootcampEnrollmentID,
		&i.AssignedBy,
		&i.AssignedAt,
		&i.DeadlineAt,
		&i.Status,
		&i.ArchivedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const checkDuplicateActiveAssignment = `-- name: CheckDuplicateActiveAssignment :one
SELECT COUNT(*) FROM assignments
WHERE assignment_group_id = $1 
  AND bootcamp_enrollment_id = $2 
  AND status = 'active'
  AND archived_at IS NULL
`

type CheckDuplicateActiveAssignmentParams struct {
	AssignmentGroupID    pgtype.UUID `db:"assignment_group_id" json:"assignment_group_id"`
	BootcampEnrollmentID pgtype.UUID `db:"bootcamp_enrollment_id" json:"bootcamp_enrollment_id"`
}

func (q *Queries) CheckDuplicateActiveAssignment(ctx context.Context, arg CheckDuplicateActiveAssignmentParams) (int64, error) {
	row := q.db.QueryRow(ctx, checkDuplicateActiveAssignment, arg.AssignmentGroupID, arg.BootcampEnrollmentID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const clearAssignmentGroupProblems = `-- name: ClearAssignmentGroupProblems :exec
DELETE FROM assignment_group_problems
WHERE assignment_group_id = $1
`

func (q *Queries) ClearAssignmentGroupProblems(ctx context.Context, assignmentGroupID pgtype.UUID) error {
	_, err := q.db.Exec(ctx, clearAssignmentGroupProblems, assignmentGroupID)
	return err
}

const countAssignmentGroupsByBootcamp = `-- name: CountAssignmentGroupsByBootcamp :one
SELECT COUNT(*) FROM assignment_groups
WHERE bootcamp_id = $1
  AND ($2::uuid IS NULL OR created_by = $2::uuid)
`

type CountAssignmentGroupsByBootcampParams struct {
	BootcampID pgtype.UUID `db:"bootcamp_id" json:"bootcamp_id"`
	CreatedBy  pgtype.UUID `db:"created_by" json:"created_by"`
}

func (q *Queries) CountAssignmentGroupsByBootcamp(ctx context.Context, arg CountAssignmentGroupsByBootcampParams) (int64, error) {
	row := q.db.QueryRow(ctx, countAssignmentGroupsByBootcamp, arg.BootcampID, arg.CreatedBy)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countAssignments = `-- name: CountAssignments :one
SELECT COUNT(*)
FROM assignments a
JOIN bootcamp_enrollments be ON a.bootcamp_enrollment_id = be.id
WHERE be.bootcamp_id = $1
  AND ($2::uuid IS NULL OR a.assignment_group_id = $2::uuid)
  AND ($3::assignment_status IS NULL OR a.status = $3::assignment_status)
  AND a.archived_at IS NULL
`

type CountAssignmentsParams struct {
	BootcampID        pgtype.UUID          `db:"bootcamp_id" json:"bootcamp_id"`
	AssignmentGroupID pgtype.UUID          `db:"assignment_group_id" json:"assignment_group_id"`
	Status            NullAssignmentStatus `db:"status" json:"status"`
}

func (q *Queries) CountAssignments(ctx context.Context, arg CountAssignmentsParams) (int64, error) {
	row := q.db.QueryRow(ctx, countAssignments, arg.BootcampID, arg.AssignmentGroupID, arg.Status)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countAssignmentsByGroup = `-- name: CountAssignmentsByGroup :one
SELECT COUNT(*) FROM assignments
WHERE assignment_group_id = $1 AND archived_at IS NULL
`

func (q *Queries) CountAssignmentsByGroup(ctx context.Context, assignmentGroupID pgtype.UUID) (int64, error) {
	row := q.db.QueryRow(ctx, countAssignmentsByGroup, assignmentGroupID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createAssignmentGroup = `-- name: CreateAssignmentGroup :one
INSERT INTO assignment_groups (
    bootcamp_id, created_by, title, description, deadline_days
) VALUES (
    $1, $2, $3, $4, $5
)
RETURNING id, bootcamp_id, created_by, title, description, deadline_days, created_at, updated_at
`

type CreateAssignmentGroupParams struct {
	BootcampID   pgtype.UUID `db:"bootcamp_id" json:"bootcamp_id"`
	CreatedBy    pgtype.UUID `db:"created_by" json:"created_by"`
	Title        string      `db:"title" json:"title"`
	Description  pgtype.Text `db:"description" json:"description"`
	DeadlineDays pgtype.Int4 `db:"deadline_days" json:"deadline_days"`
}

func (q *Queries) CreateAssignmentGroup(ctx context.Context, arg CreateAssignmentGroupParams) (AssignmentGroup, error) {
	row := q.db.QueryRow(ctx, createAssignmentGroup,
		arg.BootcampID,
		arg.CreatedBy,
		arg.Title,
		arg.Description,
		arg.DeadlineDays,
	)
	var i AssignmentGroup
	err := row.Scan(
		&i.ID,
		&i.BootcampID,
		&i.CreatedBy,
		&i.Title,
		&i.Description,
		&i.DeadlineDays,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteAssignmentGroup = `-- name: DeleteAssignmentGroup :exec
DELETE FROM assignment_groups
WHERE id = $1
`

func (q *Queries) DeleteAssignmentGroup(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, deleteAssignmentGroup, id)
	return err
}

const getAssignment = `-- name: GetAssignment :one
SELECT id, assignment_group_id, bootcamp_enrollment_id, assigned_by, assigned_at, deadline_at, status, archived_at, created_at, updated_at FROM assignments
WHERE id = $1 AND archived_at IS NULL LIMIT 1
`

func (q *Queries) GetAssignment(ctx context.Context, id pgtype.UUID) (Assignment, error) {
	row := q.db.QueryRow(ctx, getAssignment, id)
	var i Assignment
	err := row.Scan(
		&i.ID,
		&i.AssignmentGroupID,
		&i.BootcampEnrollmentID,
		&i.AssignedBy,
		&i.AssignedAt,
		&i.DeadlineAt,
		&i.Status,
		&i.ArchivedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getAssignmentGroup = `-- name: GetAssignmentGroup :one
SELECT id, bootcamp_id, created_by, title, description, deadline_days, created_at, updated_at FROM assignment_groups
WHERE id = $1 LIMIT 1
`

func (q *Queries) GetAssignmentGroup(ctx context.Context, id pgtype.UUID) (AssignmentGroup, error) {
	row := q.db.QueryRow(ctx, getAssignmentGroup, id)
	var i AssignmentGroup
	err := row.Scan(
		&i.ID,
		&i.BootcampID,
		&i.CreatedBy,
		&i.Title,
		&i.Description,
		&i.DeadlineDays,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getAssignmentWithGroup = `-- name: GetAssignmentWithGroup :one
SELECT a.id, a.assignment_group_id, a.bootcamp_enrollment_id, a.assigned_by, a.assigned_at, a.deadline_at, a.status, a.archived_at, a.created_at, a.updated_at, ag.title as group_title, ag.description as group_description
FROM assignments a
JOIN assignment_groups ag ON a.assignment_group_id = ag.id
WHERE a.id = $1 AND a.archived_at IS NULL LIMIT 1
`

type GetAssignmentWithGroupRow struct {
	ID                   pgtype.UUID        `db:"id" json:"id"`
	AssignmentGroupID    pgtype.UUID        `db:"assignment_group_id" json:"assignment_group_id"`
	BootcampEnrollmentID pgtype.UUID        `db:"bootcamp_enrollment_id" json:"bootcamp_enrollment_id"`
	AssignedBy           pgtype.UUID        `db:"assigned_by" json:"assigned_by"`
	AssignedAt           pgtype.Timestamptz `db:"assigned_at" json:"assigned_at"`
	DeadlineAt           pgtype.Timestamptz `db:"deadline_at" json:"deadline_at"`
	Status               AssignmentStatus   `db:"status" json:"status"`
	ArchivedAt           pgtype.Timestamptz `db:"archived_at" json:"archived_at"`
	CreatedAt            pgtype.Timestamptz `db:"created_at" json:"created_at"`
	UpdatedAt            pgtype.Timestamptz `db:"updated_at" json:"updated_at"`
	GroupTitle           string             `db:"group_title" json:"group_title"`
	GroupDescription     pgtype.Text        `db:"group_description" json:"group_description"`
}

func (q *Queries) GetAssignmentWithGroup(ctx context.Context, id pgtype.UUID) (GetAssignmentWithGroupRow, error) {
	row := q.db.QueryRow(ctx, getAssignmentWithGroup, id)
	var i GetAssignmentWithGroupRow
	err := row.Scan(
		&i.ID,
		&i.AssignmentGroupID,
		&i.BootcampEnrollmentID,
		&i.AssignedBy,
		&i.AssignedAt,
		&i.DeadlineAt,
		&i.Status,
		&i.ArchivedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.GroupTitle,
		&i.GroupDescription,
	)
	return i, err
}

const getEnrollmentBootcamp = `-- name: GetEnrollmentBootcamp :one
SELECT be.bootcamp_id, b.is_active
FROM bootcamp_enrollments be
JOIN bootcamps b ON be.bootcamp_id = b.id
WHERE be.id = $1
`

type GetEnrollmentBootcampRow struct {
	BootcampID pgtype.UUID `db:"bootcamp_id" json:"bootcamp_id"`
	IsActive   bool        `db:"is_active" json:"is_active"`
}

func (q *Queries) GetEnrollmentBootcamp(ctx context.Context, id pgtype.UUID) (GetEnrollmentBootcampRow, error) {
	row := q.db.QueryRow(ctx, getEnrollmentBootcamp, id)
	var i GetEnrollmentBootcampRow
	err := row.Scan(&i.BootcampID, &i.IsActive)
	return i, err
}

const initializeAssignmentProblem = `-- name: InitializeAssignmentProblem :one

INSERT INTO assignment_problems (
    assignment_id, problem_id, status
) VALUES (
    $1, $2, 'pending'
)
RETURNING id, assignment_id, problem_id, status, solution_link, notes, completed_at, created_at, updated_at
`

type InitializeAssignmentProblemParams struct {
	AssignmentID pgtype.UUID `db:"assignment_id" json:"assignment_id"`
	ProblemID    pgtype.UUID `db:"problem_id" json:"problem_id"`
}

// Assignment Problems Progress
func (q *Queries) InitializeAssignmentProblem(ctx context.Context, arg InitializeAssignmentProblemParams) (AssignmentProblem, error) {
	row := q.db.QueryRow(ctx, initializeAssignmentProblem, arg.AssignmentID, arg.ProblemID)
	var i AssignmentProblem
	err := row.Scan(
		&i.ID,
		&i.AssignmentID,
		&i.ProblemID,
		&i.Status,
		&i.SolutionLink,
		&i.Notes,
		&i.CompletedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listAssignmentGroupProblems = `-- name: ListAssignmentGroupProblems :many
SELECT p.id, p.organization_id, p.created_by, p.title, p.description, p.difficulty, p.external_link, p.archived_at, p.created_at, p.updated_at, agp.position 
FROM problems p
JOIN assignment_group_problems agp ON p.id = agp.problem_id
WHERE agp.assignment_group_id = $1
ORDER BY agp.position ASC
`

type ListAssignmentGroupProblemsRow struct {
	ID             pgtype.UUID        `db:"id" json:"id"`
	OrganizationID pgtype.UUID        `db:"organization_id" json:"organization_id"`
	CreatedBy      pgtype.UUID        `db:"created_by" json:"created_by"`
	Title          string             `db:"title" json:"title"`
	Description    pgtype.Text        `db:"description" json:"description"`
	Difficulty     DifficultyLevel    `db:"difficulty" json:"difficulty"`
	ExternalLink   pgtype.Text        `db:"external_link" json:"external_link"`
	ArchivedAt     pgtype.Timestamptz `db:"archived_at" json:"archived_at"`
	CreatedAt      pgtype.Timestamptz `db:"created_at" json:"created_at"`
	UpdatedAt      pgtype.Timestamptz `db:"updated_at" json:"updated_at"`
	Position       pgtype.Int4        `db:"position" json:"position"`
}

func (q *Queries) ListAssignmentGroupProblems(ctx context.Context, assignmentGroupID pgtype.UUID) ([]ListAssignmentGroupProblemsRow, error) {
	rows, err := q.db.Query(ctx, listAssignmentGroupProblems, assignmentGroupID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListAssignmentGroupProblemsRow{}
	for rows.Next() {
		var i ListAssignmentGroupProblemsRow
		if err := rows.Scan(
			&i.ID,
			&i.OrganizationID,
			&i.CreatedBy,
			&i.Title,
			&i.Description,
			&i.Difficulty,
			&i.ExternalLink,
			&i.ArchivedAt,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.Position,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listAssignmentGroupsByBootcamp = `-- name: ListAssignmentGroupsByBootcamp :many
SELECT id, bootcamp_id, created_by, title, description, deadline_days, created_at, updated_at FROM assignment_groups
WHERE bootcamp_id = $1
  AND ($2::uuid IS NULL OR created_by = $2::uuid)
ORDER BY created_at DESC
LIMIT $4
OFFSET $3
`

type ListAssignmentGroupsByBootcampParams struct {
	BootcampID pgtype.UUID `db:"bootcamp_id" json:"bootcamp_id"`
	CreatedBy  pgtype.UUID `db:"created_by" json:"created_by"`
	Offset     int32       `db:"offset" json:"offset"`
	Limit      int32       `db:"limit" json:"limit"`
}

func (q *Queries) ListAssignmentGroupsByBootcamp(ctx context.Context, arg ListAssignmentGroupsByBootcampParams) ([]AssignmentGroup, error) {
	rows, err := q.db.Query(ctx, listAssignmentGroupsByBootcamp,
		arg.BootcampID,
		arg.CreatedBy,
		arg.Offset,
		arg.Limit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []AssignmentGroup{}
	for rows.Next() {
		var i AssignmentGroup
		if err := rows.Scan(
			&i.ID,
			&i.BootcampID,
			&i.CreatedBy,
			&i.Title,
			&i.Description,
			&i.DeadlineDays,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listAssignmentProblemsStatus = `-- name: ListAssignmentProblemsStatus :many
SELECT ap.id, ap.assignment_id, ap.problem_id, ap.status, ap.solution_link, ap.notes, ap.completed_at, ap.created_at, ap.updated_at, p.title, p.difficulty 
FROM assignment_problems ap
JOIN problems p ON ap.problem_id = p.id
WHERE ap.assignment_id = $1
ORDER BY ap.created_at ASC
`

type ListAssignmentProblemsStatusRow struct {
	ID           pgtype.UUID             `db:"id" json:"id"`
	AssignmentID pgtype.UUID             `db:"assignment_id" json:"assignment_id"`
	ProblemID    pgtype.UUID             `db:"problem_id" json:"problem_id"`
	Status       AssignmentProblemStatus `db:"status" json:"status"`
	SolutionLink pgtype.Text             `db:"solution_link" json:"solution_link"`
	Notes        pgtype.Text             `db:"notes" json:"notes"`
	CompletedAt  pgtype.Timestamptz      `db:"completed_at" json:"completed_at"`
	CreatedAt    pgtype.Timestamptz      `db:"created_at" json:"created_at"`
	UpdatedAt    pgtype.Timestamptz      `db:"updated_at" json:"updated_at"`
	Title        string                  `db:"title" json:"title"`
	Difficulty   DifficultyLevel         `db:"difficulty" json:"difficulty"`
}

func (q *Queries) ListAssignmentProblemsStatus(ctx context.Context, assignmentID pgtype.UUID) ([]ListAssignmentProblemsStatusRow, error) {
	rows, err := q.db.Query(ctx, listAssignmentProblemsStatus, assignmentID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListAssignmentProblemsStatusRow{}
	for rows.Next() {
		var i ListAssignmentProblemsStatusRow
		if err := rows.Scan(
			&i.ID,
			&i.AssignmentID,
			&i.ProblemID,
			&i.Status,
			&i.SolutionLink,
			&i.Notes,
			&i.CompletedAt,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.Title,
			&i.Difficulty,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listAssignments = `-- name: ListAssignments :many
SELECT a.id, a.assignment_group_id, a.bootcamp_enrollment_id, a.assigned_by, a.assigned_at, a.deadline_at, a.status, a.archived_at, a.created_at, a.updated_at, ag.title as group_title
FROM assignments a
JOIN assignment_groups ag ON a.assignment_group_id = ag.id
JOIN bootcamp_enrollments be ON a.bootcamp_enrollment_id = be.id
WHERE be.bootcamp_id = $1
  AND ($2::uuid IS NULL OR a.assignment_group_id = $2::uuid)
  AND ($3::assignment_status IS NULL OR a.status = $3::assignment_status)
  AND a.archived_at IS NULL
ORDER BY a.created_at DESC
LIMIT $5
OFFSET $4
`

type ListAssignmentsParams struct {
	BootcampID        pgtype.UUID          `db:"bootcamp_id" json:"bootcamp_id"`
	AssignmentGroupID pgtype.UUID          `db:"assignment_group_id" json:"assignment_group_id"`
	Status            NullAssignmentStatus `db:"status" json:"status"`
	Offset            int32                `db:"offset" json:"offset"`
	Limit             int32                `db:"limit" json:"limit"`
}

type ListAssignmentsRow struct {
	ID                   pgtype.UUID        `db:"id" json:"id"`
	AssignmentGroupID    pgtype.UUID        `db:"assignment_group_id" json:"assignment_group_id"`
	BootcampEnrollmentID pgtype.UUID        `db:"bootcamp_enrollment_id" json:"bootcamp_enrollment_id"`
	AssignedBy           pgtype.UUID        `db:"assigned_by" json:"assigned_by"`
	AssignedAt           pgtype.Timestamptz `db:"assigned_at" json:"assigned_at"`
	DeadlineAt           pgtype.Timestamptz `db:"deadline_at" json:"deadline_at"`
	Status               AssignmentStatus   `db:"status" json:"status"`
	ArchivedAt           pgtype.Timestamptz `db:"archived_at" json:"archived_at"`
	CreatedAt            pgtype.Timestamptz `db:"created_at" json:"created_at"`
	UpdatedAt            pgtype.Timestamptz `db:"updated_at" json:"updated_at"`
	GroupTitle           string             `db:"group_title" json:"group_title"`
}

func (q *Queries) ListAssignments(ctx context.Context, arg ListAssignmentsParams) ([]ListAssignmentsRow, error) {
	rows, err := q.db.Query(ctx, listAssignments,
		arg.BootcampID,
		arg.AssignmentGroupID,
		arg.Status,
		arg.Offset,
		arg.Limit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListAssignmentsRow{}
	for rows.Next() {
		var i ListAssignmentsRow
		if err := rows.Scan(
			&i.ID,
			&i.AssignmentGroupID,
			&i.BootcampEnrollmentID,
			&i.AssignedBy,
			&i.AssignedAt,
			&i.DeadlineAt,
			&i.Status,
			&i.ArchivedAt,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.GroupTitle,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listAssignmentsByMentee = `-- name: ListAssignmentsByMentee :many
SELECT a.id, a.assignment_group_id, a.bootcamp_enrollment_id, a.assigned_by, a.assigned_at, a.deadline_at, a.status, a.archived_at, a.created_at, a.updated_at, ag.title as group_title 
FROM assignments a
JOIN assignment_groups ag ON a.assignment_group_id = ag.id
WHERE a.bootcamp_enrollment_id = $1 AND a.archived_at IS NULL
ORDER BY a.deadline_at ASC
`

type ListAssignmentsByMenteeRow struct {
	ID                   pgtype.UUID        `db:"id" json:"id"`
	AssignmentGroupID    pgtype.UUID        `db:"assignment_group_id" json:"assignment_group_id"`
	BootcampEnrollmentID pgtype.UUID        `db:"bootcamp_enrollment_id" json:"bootcamp_enrollment_id"`
	AssignedBy           pgtype.UUID        `db:"assigned_by" json:"assigned_by"`
	AssignedAt           pgtype.Timestamptz `db:"assigned_at" json:"assigned_at"`
	DeadlineAt           pgtype.Timestamptz `db:"deadline_at" json:"deadline_at"`
	Status               AssignmentStatus   `db:"status" json:"status"`
	ArchivedAt           pgtype.Timestamptz `db:"archived_at" json:"archived_at"`
	CreatedAt            pgtype.Timestamptz `db:"created_at" json:"created_at"`
	UpdatedAt            pgtype.Timestamptz `db:"updated_at" json:"updated_at"`
	GroupTitle           string             `db:"group_title" json:"group_title"`
}

func (q *Queries) ListAssignmentsByMentee(ctx context.Context, bootcampEnrollmentID pgtype.UUID) ([]ListAssignmentsByMenteeRow, error) {
	rows, err := q.db.Query(ctx, listAssignmentsByMentee, bootcampEnrollmentID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListAssignmentsByMenteeRow{}
	for rows.Next() {
		var i ListAssignmentsByMenteeRow
		if err := rows.Scan(
			&i.ID,
			&i.AssignmentGroupID,
			&i.BootcampEnrollmentID,
			&i.AssignedBy,
			&i.AssignedAt,
			&i.DeadlineAt,
			&i.Status,
			&i.ArchivedAt,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.GroupTitle,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const removeProblemFromAssignmentGroup = `-- name: RemoveProblemFromAssignmentGroup :exec
DELETE FROM assignment_group_problems
WHERE assignment_group_id = $1 AND problem_id = $2
`

type RemoveProblemFromAssignmentGroupParams struct {
	AssignmentGroupID pgtype.UUID `db:"assignment_group_id" json:"assignment_group_id"`
	ProblemID         pgtype.UUID `db:"problem_id" json:"problem_id"`
}

func (q *Queries) RemoveProblemFromAssignmentGroup(ctx context.Context, arg RemoveProblemFromAssignmentGroupParams) error {
	_, err := q.db.Exec(ctx, removeProblemFromAssignmentGroup, arg.AssignmentGroupID, arg.ProblemID)
	return err
}

const updateAssignmentDeadline = `-- name: UpdateAssignmentDeadline :one
UPDATE assignments
SET deadline_at = $2, updated_at = CURRENT_TIMESTAMP
WHERE id = $1
RETURNING id, assignment_group_id, bootcamp_enrollment_id, assigned_by, assigned_at, deadline_at, status, archived_at, created_at, updated_at
`

type UpdateAssignmentDeadlineParams struct {
	ID         pgtype.UUID        `db:"id" json:"id"`
	DeadlineAt pgtype.Timestamptz `db:"deadline_at" json:"deadline_at"`
}

func (q *Queries) UpdateAssignmentDeadline(ctx context.Context, arg UpdateAssignmentDeadlineParams) (Assignment, error) {
	row := q.db.QueryRow(ctx, updateAssignmentDeadline, arg.ID, arg.DeadlineAt)
	var i Assignment
	err := row.Scan(
		&i.ID,
		&i.AssignmentGroupID,
		&i.BootcampEnrollmentID,
		&i.AssignedBy,
		&i.AssignedAt,
		&i.DeadlineAt,
		&i.Status,
		&i.ArchivedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateAssignmentGroup = `-- name: UpdateAssignmentGroup :one
UPDATE assignment_groups
SET 
    title = COALESCE($1, title),
    description = COALESCE($2, description),
    deadline_days = COALESCE($3, deadline_days),
    updated_at = CURRENT_TIMESTAMP
WHERE id = $4
RETURNING id, bootcamp_id, created_by, title, description, deadline_days, created_at, updated_at
`

type UpdateAssignmentGroupParams struct {
	Title        pgtype.Text `db:"title" json:"title"`
	Description  pgtype.Text `db:"description" json:"description"`
	DeadlineDays pgtype.Int4 `db:"deadline_days" json:"deadline_days"`
	ID           pgtype.UUID `db:"id" json:"id"`
}

func (q *Queries) UpdateAssignmentGroup(ctx context.Context, arg UpdateAssignmentGroupParams) (AssignmentGroup, error) {
	row := q.db.QueryRow(ctx, updateAssignmentGroup,
		arg.Title,
		arg.Description,
		arg.DeadlineDays,
		arg.ID,
	)
	var i AssignmentGroup
	err := row.Scan(
		&i.ID,
		&i.BootcampID,
		&i.CreatedBy,
		&i.Title,
		&i.Description,
		&i.DeadlineDays,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateAssignmentProblemProgress = `-- name: UpdateAssignmentProblemProgress :one
UPDATE assignment_problems
SET 
    status = COALESCE($3, status),
    solution_link = COALESCE($4, solution_link),
    notes = COALESCE($5, notes),
    completed_at = COALESCE($6, completed_at),
    updated_at = CURRENT_TIMESTAMP
WHERE assignment_id = $1 AND problem_id = $2
RETURNING id, assignment_id, problem_id, status, solution_link, notes, completed_at, created_at, updated_at
`

type UpdateAssignmentProblemProgressParams struct {
	AssignmentID pgtype.UUID                 `db:"assignment_id" json:"assignment_id"`
	ProblemID    pgtype.UUID                 `db:"problem_id" json:"problem_id"`
	Status       NullAssignmentProblemStatus `db:"status" json:"status"`
	SolutionLink pgtype.Text                 `db:"solution_link" json:"solution_link"`
	Notes        pgtype.Text                 `db:"notes" json:"notes"`
	CompletedAt  pgtype.Timestamptz          `db:"completed_at" json:"completed_at"`
}

func (q *Queries) UpdateAssignmentProblemProgress(ctx context.Context, arg UpdateAssignmentProblemProgressParams) (AssignmentProblem, error) {
	row := q.db.QueryRow(ctx, updateAssignmentProblemProgress,
		arg.AssignmentID,
		arg.ProblemID,
		arg.Status,
		arg.SolutionLink,
		arg.Notes,
		arg.CompletedAt,
	)
	var i AssignmentProblem
	err := row.Scan(
		&i.ID,
		&i.AssignmentID,
		&i.ProblemID,
		&i.Status,
		&i.SolutionLink,
		&i.Notes,
		&i.CompletedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateAssignmentStatus = `-- name: UpdateAssignmentStatus :one
UPDATE assignments
SET status = $2, updated_at = CURRENT_TIMESTAMP
WHERE id = $1
RETURNING id, assignment_group_id, bootcamp_enrollment_id, assigned_by, assigned_at, deadline_at, status, archived_at, created_at, updated_at
`

type UpdateAssignmentStatusParams struct {
	ID     pgtype.UUID      `db:"id" json:"id"`
	Status AssignmentStatus `db:"status" json:"status"`
}

func (q *Queries) UpdateAssignmentStatus(ctx context.Context, arg UpdateAssignmentStatusParams) (Assignment, error) {
	row := q.db.QueryRow(ctx, updateAssignmentStatus, arg.ID, arg.Status)
	var i Assignment
	err := row.Scan(
		&i.ID,
		&i.AssignmentGroupID,
		&i.BootcampEnrollmentID,
		&i.AssignedBy,
		&i.AssignedAt,
		&i.DeadlineAt,
		&i.Status,
		&i.ArchivedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
