// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: bootcamp.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const archiveBootcamp = `-- name: ArchiveBootcamp :exec
UPDATE bootcamps
SET archived_at = CURRENT_TIMESTAMP
WHERE id = $1
`

func (q *Queries) ArchiveBootcamp(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, archiveBootcamp, id)
	return err
}

const countAllBootcamps = `-- name: CountAllBootcamps :one
SELECT COUNT(*) FROM bootcamps
WHERE archived_at IS NULL
`

func (q *Queries) CountAllBootcamps(ctx context.Context) (int64, error) {
	row := q.db.QueryRow(ctx, countAllBootcamps)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countBootcampsByEnrollment = `-- name: CountBootcampsByEnrollment :one
SELECT COUNT(DISTINCT b.id) FROM bootcamps b
JOIN bootcamp_enrollments be ON b.id = be.bootcamp_id
WHERE be.organization_member_id = $1
  AND b.archived_at IS NULL
  AND ($2::boolean IS NULL OR b.is_active = $2::boolean)
`

type CountBootcampsByEnrollmentParams struct {
	OrganizationMemberID pgtype.UUID `db:"organization_member_id" json:"organization_member_id"`
	IsActive             pgtype.Bool `db:"is_active" json:"is_active"`
}

func (q *Queries) CountBootcampsByEnrollment(ctx context.Context, arg CountBootcampsByEnrollmentParams) (int64, error) {
	row := q.db.QueryRow(ctx, countBootcampsByEnrollment, arg.OrganizationMemberID, arg.IsActive)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countBootcampsByOrg = `-- name: CountBootcampsByOrg :one
SELECT COUNT(*) FROM bootcamps
WHERE organization_id = $1 
  AND archived_at IS NULL
  AND ($2::boolean IS NULL OR is_active = $2::boolean)
`

type CountBootcampsByOrgParams struct {
	OrganizationID pgtype.UUID `db:"organization_id" json:"organization_id"`
	IsActive       pgtype.Bool `db:"is_active" json:"is_active"`
}

func (q *Queries) CountBootcampsByOrg(ctx context.Context, arg CountBootcampsByOrgParams) (int64, error) {
	row := q.db.QueryRow(ctx, countBootcampsByOrg, arg.OrganizationID, arg.IsActive)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createBootcamp = `-- name: CreateBootcamp :one
INSERT INTO bootcamps (
    organization_id, created_by, name, description, start_date, end_date, is_active
) VALUES (
    $1, $2, $3, $4, $5, $6, $7
)
RETURNING id, organization_id, created_by, name, description, start_date, end_date, is_active, archived_at, created_at, updated_at
`

type CreateBootcampParams struct {
	OrganizationID pgtype.UUID `db:"organization_id" json:"organization_id"`
	CreatedBy      pgtype.UUID `db:"created_by" json:"created_by"`
	Name           string      `db:"name" json:"name"`
	Description    pgtype.Text `db:"description" json:"description"`
	StartDate      pgtype.Date `db:"start_date" json:"start_date"`
	EndDate        pgtype.Date `db:"end_date" json:"end_date"`
	IsActive       bool        `db:"is_active" json:"is_active"`
}

func (q *Queries) CreateBootcamp(ctx context.Context, arg CreateBootcampParams) (Bootcamp, error) {
	row := q.db.QueryRow(ctx, createBootcamp,
		arg.OrganizationID,
		arg.CreatedBy,
		arg.Name,
		arg.Description,
		arg.StartDate,
		arg.EndDate,
		arg.IsActive,
	)
	var i Bootcamp
	err := row.Scan(
		&i.ID,
		&i.OrganizationID,
		&i.CreatedBy,
		&i.Name,
		&i.Description,
		&i.StartDate,
		&i.EndDate,
		&i.IsActive,
		&i.ArchivedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const enrollInBootcamp = `-- name: EnrollInBootcamp :one

INSERT INTO bootcamp_enrollments (
    bootcamp_id, organization_member_id, role, status
) VALUES (
    $1, $2, $3, $4
)
RETURNING id, bootcamp_id, organization_member_id, role, status, enrolled_at, assigned_sheet_key
`

type EnrollInBootcampParams struct {
	BootcampID           pgtype.UUID            `db:"bootcamp_id" json:"bootcamp_id"`
	OrganizationMemberID pgtype.UUID            `db:"organization_member_id" json:"organization_member_id"`
	Role                 BootcampEnrollmentRole `db:"role" json:"role"`
	Status               EnrollmentStatus       `db:"status" json:"status"`
}

// Enrollment
func (q *Queries) EnrollInBootcamp(ctx context.Context, arg EnrollInBootcampParams) (BootcampEnrollment, error) {
	row := q.db.QueryRow(ctx, enrollInBootcamp,
		arg.BootcampID,
		arg.OrganizationMemberID,
		arg.Role,
		arg.Status,
	)
	var i BootcampEnrollment
	err := row.Scan(
		&i.ID,
		&i.BootcampID,
		&i.OrganizationMemberID,
		&i.Role,
		&i.Status,
		&i.EnrolledAt,
		&i.AssignedSheetKey,
	)
	return i, err
}

const getBootcamp = `-- name: GetBootcamp :one
SELECT id, organization_id, created_by, name, description, start_date, end_date, is_active, archived_at, created_at, updated_at FROM bootcamps
WHERE id = $1 AND archived_at IS NULL LIMIT 1
`

func (q *Queries) GetBootcamp(ctx context.Context, id pgtype.UUID) (Bootcamp, error) {
	row := q.db.QueryRow(ctx, getBootcamp, id)
	var i Bootcamp
	err := row.Scan(
		&i.ID,
		&i.OrganizationID,
		&i.CreatedBy,
		&i.Name,
		&i.Description,
		&i.StartDate,
		&i.EndDate,
		&i.IsActive,
		&i.ArchivedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getEnrollment = `-- name: GetEnrollment :one
SELECT id, bootcamp_id, organization_member_id, role, status, enrolled_at, assigned_sheet_key FROM bootcamp_enrollments
WHERE id = $1 LIMIT 1
`

func (q *Queries) GetEnrollment(ctx context.Context, id pgtype.UUID) (BootcampEnrollment, error) {
	row := q.db.QueryRow(ctx, getEnrollment, id)
	var i BootcampEnrollment
	err := row.Scan(
		&i.ID,
		&i.BootcampID,
		&i.OrganizationMemberID,
		&i.Role,
		&i.Status,
		&i.EnrolledAt,
		&i.AssignedSheetKey,
	)
	return i, err
}

const getEnrollmentByMember = `-- name: GetEnrollmentByMember :one
SELECT id, bootcamp_id, organization_member_id, role, status, enrolled_at, assigned_sheet_key FROM bootcamp_enrollments
WHERE bootcamp_id = $1 AND organization_member_id = $2 LIMIT 1
`

type GetEnrollmentByMemberParams struct {
	BootcampID           pgtype.UUID `db:"bootcamp_id" json:"bootcamp_id"`
	OrganizationMemberID pgtype.UUID `db:"organization_member_id" json:"organization_member_id"`
}

func (q *Queries) GetEnrollmentByMember(ctx context.Context, arg GetEnrollmentByMemberParams) (BootcampEnrollment, error) {
	row := q.db.QueryRow(ctx, getEnrollmentByMember, arg.BootcampID, arg.OrganizationMemberID)
	var i BootcampEnrollment
	err := row.Scan(
		&i.ID,
		&i.BootcampID,
		&i.OrganizationMemberID,
		&i.Role,
		&i.Status,
		&i.EnrolledAt,
		&i.AssignedSheetKey,
	)
	return i, err
}

const getEnrollmentIDByUserID = `-- name: GetEnrollmentIDByUserID :one
SELECT be.id FROM bootcamp_enrollments be
JOIN organization_members om ON be.organization_member_id = om.id
WHERE om.user_id = $1 AND be.bootcamp_id = $2
LIMIT 1
`

type GetEnrollmentIDByUserIDParams struct {
	UserID     pgtype.UUID `db:"user_id" json:"user_id"`
	BootcampID pgtype.UUID `db:"bootcamp_id" json:"bootcamp_id"`
}

func (q *Queries) GetEnrollmentIDByUserID(ctx context.Context, arg GetEnrollmentIDByUserIDParams) (pgtype.UUID, error) {
	row := q.db.QueryRow(ctx, getEnrollmentIDByUserID, arg.UserID, arg.BootcampID)
	var id pgtype.UUID
	err := row.Scan(&id)
	return id, err
}

const listAllBootcamps = `-- name: ListAllBootcamps :many

SELECT b.id, b.organization_id, b.created_by, b.name, b.description, b.start_date, b.end_date, b.is_active, b.archived_at, b.created_at, b.updated_at, o.name as organization_name, o.slug as organization_slug
FROM bootcamps b
JOIN organizations o ON b.organization_id = o.id
WHERE b.archived_at IS NULL
ORDER BY b.created_at DESC
LIMIT $1 OFFSET $2
`

type ListAllBootcampsParams struct {
	Limit  int32 `db:"limit" json:"limit"`
	Offset int32 `db:"offset" json:"offset"`
}

type ListAllBootcampsRow struct {
	ID               pgtype.UUID        `db:"id" json:"id"`
	OrganizationID   pgtype.UUID        `db:"organization_id" json:"organization_id"`
	CreatedBy        pgtype.UUID        `db:"created_by" json:"created_by"`
	Name             string             `db:"name" json:"name"`
	Description      pgtype.Text        `db:"description" json:"description"`
	StartDate        pgtype.Date        `db:"start_date" json:"start_date"`
	EndDate          pgtype.Date        `db:"end_date" json:"end_date"`
	IsActive         bool               `db:"is_active" json:"is_active"`
	ArchivedAt       pgtype.Timestamptz `db:"archived_at" json:"archived_at"`
	CreatedAt        pgtype.Timestamptz `db:"created_at" json:"created_at"`
	UpdatedAt        pgtype.Timestamptz `db:"updated_at" json:"updated_at"`
	OrganizationName string             `db:"organization_name" json:"organization_name"`
	OrganizationSlug string             `db:"organization_slug" json:"organization_slug"`
}

// Super Admin Queries
func (q *Queries) ListAllBootcamps(ctx context.Context, arg ListAllBootcampsParams) ([]ListAllBootcampsRow, error) {
	rows, err := q.db.Query(ctx, listAllBootcamps, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListAllBootcampsRow{}
	for rows.Next() {
		var i ListAllBootcampsRow
		if err := rows.Scan(
			&i.ID,
			&i.OrganizationID,
			&i.CreatedBy,
			&i.Name,
			&i.Description,
			&i.StartDate,
			&i.EndDate,
			&i.IsActive,
			&i.ArchivedAt,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.OrganizationName,
			&i.OrganizationSlug,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listBootcampEnrollments = `-- name: ListBootcampEnrollments :many
SELECT be.id, be.bootcamp_id, be.organization_member_id, be.role, be.status, be.enrolled_at, be.assigned_sheet_key, u.name, u.email, u.avatar_url, om.role as org_role
FROM bootcamp_enrollments be
JOIN organization_members om ON be.organization_member_id = om.id
JOIN users u ON om.user_id = u.id
WHERE be.bootcamp_id = $1
ORDER BY be.enrolled_at ASC
`

type ListBootcampEnrollmentsRow struct {
	ID                   pgtype.UUID            `db:"id" json:"id"`
	BootcampID           pgtype.UUID            `db:"bootcamp_id" json:"bootcamp_id"`
	OrganizationMemberID pgtype.UUID            `db:"organization_member_id" json:"organization_member_id"`
	Role                 BootcampEnrollmentRole `db:"role" json:"role"`
	Status               EnrollmentStatus       `db:"status" json:"status"`
	EnrolledAt           pgtype.Timestamptz     `db:"enrolled_at" json:"enrolled_at"`
	AssignedSheetKey     pgtype.Text            `db:"assigned_sheet_key" json:"assigned_sheet_key"`
	Name                 string                 `db:"name" json:"name"`
	Email                pgtype.Text            `db:"email" json:"email"`
	AvatarUrl            pgtype.Text            `db:"avatar_url" json:"avatar_url"`
	OrgRole              OrgMemberRole          `db:"org_role" json:"org_role"`
}

func (q *Queries) ListBootcampEnrollments(ctx context.Context, bootcampID pgtype.UUID) ([]ListBootcampEnrollmentsRow, error) {
	rows, err := q.db.Query(ctx, listBootcampEnrollments, bootcampID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListBootcampEnrollmentsRow{}
	for rows.Next() {
		var i ListBootcampEnrollmentsRow
		if err := rows.Scan(
			&i.ID,
			&i.BootcampID,
			&i.OrganizationMemberID,
			&i.Role,
			&i.Status,
			&i.EnrolledAt,
			&i.AssignedSheetKey,
			&i.Name,
			&i.Email,
			&i.AvatarUrl,
			&i.OrgRole,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listBootcampsByEnrollment = `-- name: ListBootcampsByEnrollment :many
SELECT DISTINCT b.id, b.organization_id, b.created_by, b.name, b.description, b.start_date, b.end_date, b.is_active, b.archived_at, b.created_at, b.updated_at FROM bootcamps b
JOIN bootcamp_enrollments be ON b.id = be.bootcamp_id
WHERE be.organization_member_id = $1
  AND b.archived_at IS NULL
  AND ($4::boolean IS NULL OR b.is_active = $4::boolean)
ORDER BY b.created_at DESC
LIMIT $2 OFFSET $3
`

type ListBootcampsByEnrollmentParams struct {
	OrganizationMemberID pgtype.UUID `db:"organization_member_id" json:"organization_member_id"`
	Limit                int32       `db:"limit" json:"limit"`
	Offset               int32       `db:"offset" json:"offset"`
	IsActive             pgtype.Bool `db:"is_active" json:"is_active"`
}

func (q *Queries) ListBootcampsByEnrollment(ctx context.Context, arg ListBootcampsByEnrollmentParams) ([]Bootcamp, error) {
	rows, err := q.db.Query(ctx, listBootcampsByEnrollment,
		arg.OrganizationMemberID,
		arg.Limit,
		arg.Offset,
		arg.IsActive,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Bootcamp{}
	for rows.Next() {
		var i Bootcamp
		if err := rows.Scan(
			&i.ID,
			&i.OrganizationID,
			&i.CreatedBy,
			&i.Name,
			&i.Description,
			&i.StartDate,
			&i.EndDate,
			&i.IsActive,
			&i.ArchivedAt,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listBootcampsByOrg = `-- name: ListBootcampsByOrg :many
SELECT id, organization_id, created_by, name, description, start_date, end_date, is_active, archived_at, created_at, updated_at FROM bootcamps
WHERE organization_id = $1 AND archived_at IS NULL
ORDER BY created_at DESC
`

func (q *Queries) ListBootcampsByOrg(ctx context.Context, organizationID pgtype.UUID) ([]Bootcamp, error) {
	rows, err := q.db.Query(ctx, listBootcampsByOrg, organizationID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Bootcamp{}
	for rows.Next() {
		var i Bootcamp
		if err := rows.Scan(
			&i.ID,
			&i.OrganizationID,
			&i.CreatedBy,
			&i.Name,
			&i.Description,
			&i.StartDate,
			&i.EndDate,
			&i.IsActive,
			&i.ArchivedAt,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listBootcampsByOrgWithPagination = `-- name: ListBootcampsByOrgWithPagination :many
SELECT id, organization_id, created_by, name, description, start_date, end_date, is_active, archived_at, created_at, updated_at FROM bootcamps
WHERE organization_id = $1 
  AND archived_at IS NULL
  AND ($4::boolean IS NULL OR is_active = $4::boolean)
ORDER BY created_at DESC
LIMIT $2 OFFSET $3
`

type ListBootcampsByOrgWithPaginationParams struct {
	OrganizationID pgtype.UUID `db:"organization_id" json:"organization_id"`
	Limit          int32       `db:"limit" json:"limit"`
	Offset         int32       `db:"offset" json:"offset"`
	IsActive       pgtype.Bool `db:"is_active" json:"is_active"`
}

func (q *Queries) ListBootcampsByOrgWithPagination(ctx context.Context, arg ListBootcampsByOrgWithPaginationParams) ([]Bootcamp, error) {
	rows, err := q.db.Query(ctx, listBootcampsByOrgWithPagination,
		arg.OrganizationID,
		arg.Limit,
		arg.Offset,
		arg.IsActive,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Bootcamp{}
	for rows.Next() {
		var i Bootcamp
		if err := rows.Scan(
			&i.ID,
			&i.OrganizationID,
			&i.CreatedBy,
			&i.Name,
			&i.Description,
			&i.StartDate,
			&i.EndDate,
			&i.IsActive,
			&i.ArchivedAt,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const removeEnrollment = `-- name: RemoveEnrollment :exec
DELETE FROM bootcamp_enrollments
WHERE id = $1
`

func (q *Queries) RemoveEnrollment(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, removeEnrollment, id)
	return err
}

const updateBootcamp = `-- name: UpdateBootcamp :one
UPDATE bootcamps
SET 
    name = COALESCE($2, name),
    description = COALESCE($3, description),
    start_date = COALESCE($4, start_date),
    end_date = COALESCE($5, end_date),
    is_active = COALESCE($6, is_active),
    updated_at = CURRENT_TIMESTAMP
WHERE id = $1
RETURNING id, organization_id, created_by, name, description, start_date, end_date, is_active, archived_at, created_at, updated_at
`

type UpdateBootcampParams struct {
	ID          pgtype.UUID `db:"id" json:"id"`
	Name        pgtype.Text `db:"name" json:"name"`
	Description pgtype.Text `db:"description" json:"description"`
	StartDate   pgtype.Date `db:"start_date" json:"start_date"`
	EndDate     pgtype.Date `db:"end_date" json:"end_date"`
	IsActive    pgtype.Bool `db:"is_active" json:"is_active"`
}

func (q *Queries) UpdateBootcamp(ctx context.Context, arg UpdateBootcampParams) (Bootcamp, error) {
	row := q.db.QueryRow(ctx, updateBootcamp,
		arg.ID,
		arg.Name,
		arg.Description,
		arg.StartDate,
		arg.EndDate,
		arg.IsActive,
	)
	var i Bootcamp
	err := row.Scan(
		&i.ID,
		&i.OrganizationID,
		&i.CreatedBy,
		&i.Name,
		&i.Description,
		&i.StartDate,
		&i.EndDate,
		&i.IsActive,
		&i.ArchivedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateEnrollmentRole = `-- name: UpdateEnrollmentRole :one
UPDATE bootcamp_enrollments
SET role = $2
WHERE id = $1
RETURNING id, bootcamp_id, organization_member_id, role, status, enrolled_at, assigned_sheet_key
`

type UpdateEnrollmentRoleParams struct {
	ID   pgtype.UUID            `db:"id" json:"id"`
	Role BootcampEnrollmentRole `db:"role" json:"role"`
}

func (q *Queries) UpdateEnrollmentRole(ctx context.Context, arg UpdateEnrollmentRoleParams) (BootcampEnrollment, error) {
	row := q.db.QueryRow(ctx, updateEnrollmentRole, arg.ID, arg.Role)
	var i BootcampEnrollment
	err := row.Scan(
		&i.ID,
		&i.BootcampID,
		&i.OrganizationMemberID,
		&i.Role,
		&i.Status,
		&i.EnrolledAt,
		&i.AssignedSheetKey,
	)
	return i, err
}

const updateEnrollmentStatus = `-- name: UpdateEnrollmentStatus :one
UPDATE bootcamp_enrollments
SET status = $2
WHERE id = $1
RETURNING id, bootcamp_id, organization_member_id, role, status, enrolled_at, assigned_sheet_key
`

type UpdateEnrollmentStatusParams struct {
	ID     pgtype.UUID      `db:"id" json:"id"`
	Status EnrollmentStatus `db:"status" json:"status"`
}

func (q *Queries) UpdateEnrollmentStatus(ctx context.Context, arg UpdateEnrollmentStatusParams) (BootcampEnrollment, error) {
	row := q.db.QueryRow(ctx, updateEnrollmentStatus, arg.ID, arg.Status)
	var i BootcampEnrollment
	err := row.Scan(
		&i.ID,
		&i.BootcampID,
		&i.OrganizationMemberID,
		&i.Role,
		&i.Status,
		&i.EnrolledAt,
		&i.AssignedSheetKey,
	)
	return i, err
}
