// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: doubt.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createDoubt = `-- name: CreateDoubt :one
INSERT INTO doubts (
    assignment_problem_id, raised_by, message
) VALUES (
    $1, $2, $3
)
RETURNING id, assignment_problem_id, raised_by, message, resolved, resolved_by, resolved_at, created_at
`

type CreateDoubtParams struct {
	AssignmentProblemID pgtype.UUID `db:"assignment_problem_id" json:"assignment_problem_id"`
	RaisedBy            pgtype.UUID `db:"raised_by" json:"raised_by"`
	Message             string      `db:"message" json:"message"`
}

func (q *Queries) CreateDoubt(ctx context.Context, arg CreateDoubtParams) (Doubt, error) {
	row := q.db.QueryRow(ctx, createDoubt, arg.AssignmentProblemID, arg.RaisedBy, arg.Message)
	var i Doubt
	err := row.Scan(
		&i.ID,
		&i.AssignmentProblemID,
		&i.RaisedBy,
		&i.Message,
		&i.Resolved,
		&i.ResolvedBy,
		&i.ResolvedAt,
		&i.CreatedAt,
	)
	return i, err
}

const getDoubt = `-- name: GetDoubt :one
SELECT id, assignment_problem_id, raised_by, message, resolved, resolved_by, resolved_at, created_at FROM doubts
WHERE id = $1 LIMIT 1
`

func (q *Queries) GetDoubt(ctx context.Context, id pgtype.UUID) (Doubt, error) {
	row := q.db.QueryRow(ctx, getDoubt, id)
	var i Doubt
	err := row.Scan(
		&i.ID,
		&i.AssignmentProblemID,
		&i.RaisedBy,
		&i.Message,
		&i.Resolved,
		&i.ResolvedBy,
		&i.ResolvedAt,
		&i.CreatedAt,
	)
	return i, err
}

const listDoubtsByAssignmentProblem = `-- name: ListDoubtsByAssignmentProblem :many
SELECT d.id, d.assignment_problem_id, d.raised_by, d.message, d.resolved, d.resolved_by, d.resolved_at, d.created_at, u.name as raised_by_name 
FROM doubts d
JOIN organization_members om ON d.raised_by = om.id
JOIN users u ON om.user_id = u.id
WHERE d.assignment_problem_id = $1
ORDER BY d.created_at DESC
`

type ListDoubtsByAssignmentProblemRow struct {
	ID                  pgtype.UUID        `db:"id" json:"id"`
	AssignmentProblemID pgtype.UUID        `db:"assignment_problem_id" json:"assignment_problem_id"`
	RaisedBy            pgtype.UUID        `db:"raised_by" json:"raised_by"`
	Message             string             `db:"message" json:"message"`
	Resolved            bool               `db:"resolved" json:"resolved"`
	ResolvedBy          pgtype.UUID        `db:"resolved_by" json:"resolved_by"`
	ResolvedAt          pgtype.Timestamptz `db:"resolved_at" json:"resolved_at"`
	CreatedAt           pgtype.Timestamptz `db:"created_at" json:"created_at"`
	RaisedByName        string             `db:"raised_by_name" json:"raised_by_name"`
}

func (q *Queries) ListDoubtsByAssignmentProblem(ctx context.Context, assignmentProblemID pgtype.UUID) ([]ListDoubtsByAssignmentProblemRow, error) {
	rows, err := q.db.Query(ctx, listDoubtsByAssignmentProblem, assignmentProblemID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListDoubtsByAssignmentProblemRow{}
	for rows.Next() {
		var i ListDoubtsByAssignmentProblemRow
		if err := rows.Scan(
			&i.ID,
			&i.AssignmentProblemID,
			&i.RaisedBy,
			&i.Message,
			&i.Resolved,
			&i.ResolvedBy,
			&i.ResolvedAt,
			&i.CreatedAt,
			&i.RaisedByName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPendingDoubtsByBootcamp = `-- name: ListPendingDoubtsByBootcamp :many
SELECT d.id, d.assignment_problem_id, d.raised_by, d.message, d.resolved, d.resolved_by, d.resolved_at, d.created_at, p.title as problem_title, u.name as mentee_name
FROM doubts d
JOIN assignment_problems ap ON d.assignment_problem_id = ap.id
JOIN assignments a ON ap.assignment_id = a.id
JOIN problems p ON ap.problem_id = p.id
JOIN organization_members om ON d.raised_by = om.id
JOIN users u ON om.user_id = u.id
JOIN bootcamp_enrollments be ON a.bootcamp_enrollment_id = be.id
WHERE be.bootcamp_id = $1 AND d.resolved = FALSE
ORDER BY d.created_at ASC
`

type ListPendingDoubtsByBootcampRow struct {
	ID                  pgtype.UUID        `db:"id" json:"id"`
	AssignmentProblemID pgtype.UUID        `db:"assignment_problem_id" json:"assignment_problem_id"`
	RaisedBy            pgtype.UUID        `db:"raised_by" json:"raised_by"`
	Message             string             `db:"message" json:"message"`
	Resolved            bool               `db:"resolved" json:"resolved"`
	ResolvedBy          pgtype.UUID        `db:"resolved_by" json:"resolved_by"`
	ResolvedAt          pgtype.Timestamptz `db:"resolved_at" json:"resolved_at"`
	CreatedAt           pgtype.Timestamptz `db:"created_at" json:"created_at"`
	ProblemTitle        string             `db:"problem_title" json:"problem_title"`
	MenteeName          string             `db:"mentee_name" json:"mentee_name"`
}

func (q *Queries) ListPendingDoubtsByBootcamp(ctx context.Context, bootcampID pgtype.UUID) ([]ListPendingDoubtsByBootcampRow, error) {
	rows, err := q.db.Query(ctx, listPendingDoubtsByBootcamp, bootcampID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListPendingDoubtsByBootcampRow{}
	for rows.Next() {
		var i ListPendingDoubtsByBootcampRow
		if err := rows.Scan(
			&i.ID,
			&i.AssignmentProblemID,
			&i.RaisedBy,
			&i.Message,
			&i.Resolved,
			&i.ResolvedBy,
			&i.ResolvedAt,
			&i.CreatedAt,
			&i.ProblemTitle,
			&i.MenteeName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const resolveDoubt = `-- name: ResolveDoubt :one
UPDATE doubts
SET 
    resolved = TRUE,
    resolved_by = $2,
    resolved_at = CURRENT_TIMESTAMP
WHERE id = $1
RETURNING id, assignment_problem_id, raised_by, message, resolved, resolved_by, resolved_at, created_at
`

type ResolveDoubtParams struct {
	ID         pgtype.UUID `db:"id" json:"id"`
	ResolvedBy pgtype.UUID `db:"resolved_by" json:"resolved_by"`
}

func (q *Queries) ResolveDoubt(ctx context.Context, arg ResolveDoubtParams) (Doubt, error) {
	row := q.db.QueryRow(ctx, resolveDoubt, arg.ID, arg.ResolvedBy)
	var i Doubt
	err := row.Scan(
		&i.ID,
		&i.AssignmentProblemID,
		&i.RaisedBy,
		&i.Message,
		&i.Resolved,
		&i.ResolvedBy,
		&i.ResolvedAt,
		&i.CreatedAt,
	)
	return i, err
}
