// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: organization.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const addOrganizationMember = `-- name: AddOrganizationMember :one

INSERT INTO organization_members (
    organization_id, user_id, role
) VALUES (
    $1, $2, $3
)
RETURNING id, organization_id, user_id, role, joined_at
`

type AddOrganizationMemberParams struct {
	OrganizationID pgtype.UUID   `db:"organization_id" json:"organization_id"`
	UserID         pgtype.UUID   `db:"user_id" json:"user_id"`
	Role           OrgMemberRole `db:"role" json:"role"`
}

// Member management
func (q *Queries) AddOrganizationMember(ctx context.Context, arg AddOrganizationMemberParams) (OrganizationMember, error) {
	row := q.db.QueryRow(ctx, addOrganizationMember, arg.OrganizationID, arg.UserID, arg.Role)
	var i OrganizationMember
	err := row.Scan(
		&i.ID,
		&i.OrganizationID,
		&i.UserID,
		&i.Role,
		&i.JoinedAt,
	)
	return i, err
}

const countAllOrganizations = `-- name: CountAllOrganizations :one
SELECT COUNT(*) FROM organizations
`

func (q *Queries) CountAllOrganizations(ctx context.Context) (int64, error) {
	row := q.db.QueryRow(ctx, countAllOrganizations)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countOrganizationAdmins = `-- name: CountOrganizationAdmins :one
SELECT COUNT(*) FROM organization_members
WHERE organization_id = $1 AND role = 'admin'
`

func (q *Queries) CountOrganizationAdmins(ctx context.Context, organizationID pgtype.UUID) (int64, error) {
	row := q.db.QueryRow(ctx, countOrganizationAdmins, organizationID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countOrganizationMembers = `-- name: CountOrganizationMembers :one
SELECT COUNT(*) FROM organization_members
WHERE organization_id = $1
`

func (q *Queries) CountOrganizationMembers(ctx context.Context, organizationID pgtype.UUID) (int64, error) {
	row := q.db.QueryRow(ctx, countOrganizationMembers, organizationID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countUserOrganizations = `-- name: CountUserOrganizations :one
SELECT COUNT(*) FROM organizations o
JOIN organization_members om ON o.id = om.organization_id
WHERE om.user_id = $1
`

func (q *Queries) CountUserOrganizations(ctx context.Context, userID pgtype.UUID) (int64, error) {
	row := q.db.QueryRow(ctx, countUserOrganizations, userID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createOrganization = `-- name: CreateOrganization :one
INSERT INTO organizations (
    name, slug, description, status
) VALUES (
    $1, $2, $3, $4
)
RETURNING id, name, slug, description, status, created_at, updated_at
`

type CreateOrganizationParams struct {
	Name        string      `db:"name" json:"name"`
	Slug        string      `db:"slug" json:"slug"`
	Description pgtype.Text `db:"description" json:"description"`
	Status      OrgStatus   `db:"status" json:"status"`
}

func (q *Queries) CreateOrganization(ctx context.Context, arg CreateOrganizationParams) (Organization, error) {
	row := q.db.QueryRow(ctx, createOrganization,
		arg.Name,
		arg.Slug,
		arg.Description,
		arg.Status,
	)
	var i Organization
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Slug,
		&i.Description,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getOrganizationById = `-- name: GetOrganizationById :one
SELECT id, name, slug, description, status, created_at, updated_at FROM organizations
WHERE id = $1 LIMIT 1
`

func (q *Queries) GetOrganizationById(ctx context.Context, id pgtype.UUID) (Organization, error) {
	row := q.db.QueryRow(ctx, getOrganizationById, id)
	var i Organization
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Slug,
		&i.Description,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getOrganizationBySlug = `-- name: GetOrganizationBySlug :one
SELECT id, name, slug, description, status, created_at, updated_at FROM organizations
WHERE slug = $1 LIMIT 1
`

func (q *Queries) GetOrganizationBySlug(ctx context.Context, slug string) (Organization, error) {
	row := q.db.QueryRow(ctx, getOrganizationBySlug, slug)
	var i Organization
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Slug,
		&i.Description,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getOrganizationMember = `-- name: GetOrganizationMember :one
SELECT id, organization_id, user_id, role, joined_at FROM organization_members
WHERE organization_id = $1 AND user_id = $2 LIMIT 1
`

type GetOrganizationMemberParams struct {
	OrganizationID pgtype.UUID `db:"organization_id" json:"organization_id"`
	UserID         pgtype.UUID `db:"user_id" json:"user_id"`
}

func (q *Queries) GetOrganizationMember(ctx context.Context, arg GetOrganizationMemberParams) (OrganizationMember, error) {
	row := q.db.QueryRow(ctx, getOrganizationMember, arg.OrganizationID, arg.UserID)
	var i OrganizationMember
	err := row.Scan(
		&i.ID,
		&i.OrganizationID,
		&i.UserID,
		&i.Role,
		&i.JoinedAt,
	)
	return i, err
}

const getOrganizationMemberById = `-- name: GetOrganizationMemberById :one
SELECT id, organization_id, user_id, role, joined_at FROM organization_members
WHERE id = $1 LIMIT 1
`

func (q *Queries) GetOrganizationMemberById(ctx context.Context, id pgtype.UUID) (OrganizationMember, error) {
	row := q.db.QueryRow(ctx, getOrganizationMemberById, id)
	var i OrganizationMember
	err := row.Scan(
		&i.ID,
		&i.OrganizationID,
		&i.UserID,
		&i.Role,
		&i.JoinedAt,
	)
	return i, err
}

const getPendingOrganizations = `-- name: GetPendingOrganizations :many
SELECT id, name, slug, description, status, created_at, updated_at FROM organizations
WHERE status = 'pending_approval'
ORDER BY created_at ASC
`

func (q *Queries) GetPendingOrganizations(ctx context.Context) ([]Organization, error) {
	rows, err := q.db.Query(ctx, getPendingOrganizations)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Organization{}
	for rows.Next() {
		var i Organization
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Slug,
			&i.Description,
			&i.Status,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listAllOrganizations = `-- name: ListAllOrganizations :many

SELECT id, name, slug, description, status, created_at, updated_at FROM organizations
ORDER BY created_at DESC
LIMIT $1 OFFSET $2
`

type ListAllOrganizationsParams struct {
	Limit  int32 `db:"limit" json:"limit"`
	Offset int32 `db:"offset" json:"offset"`
}

// Super Admin Queries
func (q *Queries) ListAllOrganizations(ctx context.Context, arg ListAllOrganizationsParams) ([]Organization, error) {
	rows, err := q.db.Query(ctx, listAllOrganizations, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Organization{}
	for rows.Next() {
		var i Organization
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Slug,
			&i.Description,
			&i.Status,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listOrganizationMembers = `-- name: ListOrganizationMembers :many
SELECT om.id, om.organization_id, om.user_id, om.role, om.joined_at, u.name, u.email, u.avatar_url 
FROM organization_members om
JOIN users u ON om.user_id = u.id
WHERE om.organization_id = $1
ORDER BY om.joined_at ASC
LIMIT $2 OFFSET $3
`

type ListOrganizationMembersParams struct {
	OrganizationID pgtype.UUID `db:"organization_id" json:"organization_id"`
	Limit          int32       `db:"limit" json:"limit"`
	Offset         int32       `db:"offset" json:"offset"`
}

type ListOrganizationMembersRow struct {
	ID             pgtype.UUID        `db:"id" json:"id"`
	OrganizationID pgtype.UUID        `db:"organization_id" json:"organization_id"`
	UserID         pgtype.UUID        `db:"user_id" json:"user_id"`
	Role           OrgMemberRole      `db:"role" json:"role"`
	JoinedAt       pgtype.Timestamptz `db:"joined_at" json:"joined_at"`
	Name           string             `db:"name" json:"name"`
	Email          pgtype.Text        `db:"email" json:"email"`
	AvatarUrl      pgtype.Text        `db:"avatar_url" json:"avatar_url"`
}

func (q *Queries) ListOrganizationMembers(ctx context.Context, arg ListOrganizationMembersParams) ([]ListOrganizationMembersRow, error) {
	rows, err := q.db.Query(ctx, listOrganizationMembers, arg.OrganizationID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListOrganizationMembersRow{}
	for rows.Next() {
		var i ListOrganizationMembersRow
		if err := rows.Scan(
			&i.ID,
			&i.OrganizationID,
			&i.UserID,
			&i.Role,
			&i.JoinedAt,
			&i.Name,
			&i.Email,
			&i.AvatarUrl,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listOrganizations = `-- name: ListOrganizations :many
SELECT o.id, o.name, o.slug, o.description, o.status, o.created_at, o.updated_at FROM organizations o
JOIN organization_members om ON o.id = om.organization_id
WHERE om.user_id = $1
ORDER BY o.created_at DESC
LIMIT $2 OFFSET $3
`

type ListOrganizationsParams struct {
	UserID pgtype.UUID `db:"user_id" json:"user_id"`
	Limit  int32       `db:"limit" json:"limit"`
	Offset int32       `db:"offset" json:"offset"`
}

func (q *Queries) ListOrganizations(ctx context.Context, arg ListOrganizationsParams) ([]Organization, error) {
	rows, err := q.db.Query(ctx, listOrganizations, arg.UserID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Organization{}
	for rows.Next() {
		var i Organization
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Slug,
			&i.Description,
			&i.Status,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const removeOrganizationMember = `-- name: RemoveOrganizationMember :exec
DELETE FROM organization_members
WHERE organization_id = $1 AND user_id = $2
`

type RemoveOrganizationMemberParams struct {
	OrganizationID pgtype.UUID `db:"organization_id" json:"organization_id"`
	UserID         pgtype.UUID `db:"user_id" json:"user_id"`
}

func (q *Queries) RemoveOrganizationMember(ctx context.Context, arg RemoveOrganizationMemberParams) error {
	_, err := q.db.Exec(ctx, removeOrganizationMember, arg.OrganizationID, arg.UserID)
	return err
}

const updateOrganization = `-- name: UpdateOrganization :one
UPDATE organizations
SET 
    name = COALESCE($2, name),
    slug = COALESCE($3, slug),
    description = COALESCE($4, description),
    status = COALESCE($5, status),
    updated_at = CURRENT_TIMESTAMP
WHERE id = $1
RETURNING id, name, slug, description, status, created_at, updated_at
`

type UpdateOrganizationParams struct {
	ID          pgtype.UUID   `db:"id" json:"id"`
	Name        pgtype.Text   `db:"name" json:"name"`
	Slug        pgtype.Text   `db:"slug" json:"slug"`
	Description pgtype.Text   `db:"description" json:"description"`
	Status      NullOrgStatus `db:"status" json:"status"`
}

func (q *Queries) UpdateOrganization(ctx context.Context, arg UpdateOrganizationParams) (Organization, error) {
	row := q.db.QueryRow(ctx, updateOrganization,
		arg.ID,
		arg.Name,
		arg.Slug,
		arg.Description,
		arg.Status,
	)
	var i Organization
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Slug,
		&i.Description,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateOrganizationMemberRole = `-- name: UpdateOrganizationMemberRole :one
UPDATE organization_members
SET role = $3
WHERE organization_id = $1 AND user_id = $2
RETURNING id, organization_id, user_id, role, joined_at
`

type UpdateOrganizationMemberRoleParams struct {
	OrganizationID pgtype.UUID   `db:"organization_id" json:"organization_id"`
	UserID         pgtype.UUID   `db:"user_id" json:"user_id"`
	Role           OrgMemberRole `db:"role" json:"role"`
}

func (q *Queries) UpdateOrganizationMemberRole(ctx context.Context, arg UpdateOrganizationMemberRoleParams) (OrganizationMember, error) {
	row := q.db.QueryRow(ctx, updateOrganizationMemberRole, arg.OrganizationID, arg.UserID, arg.Role)
	var i OrganizationMember
	err := row.Scan(
		&i.ID,
		&i.OrganizationID,
		&i.UserID,
		&i.Role,
		&i.JoinedAt,
	)
	return i, err
}
