// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: problem.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const addProblemResource = `-- name: AddProblemResource :one

INSERT INTO problem_resources (
    problem_id, title, url
) VALUES (
    $1, $2, $3
)
RETURNING id, problem_id, title, url, created_at
`

type AddProblemResourceParams struct {
	ProblemID pgtype.UUID `db:"problem_id" json:"problem_id"`
	Title     pgtype.Text `db:"title" json:"title"`
	Url       pgtype.Text `db:"url" json:"url"`
}

// Resources
func (q *Queries) AddProblemResource(ctx context.Context, arg AddProblemResourceParams) (ProblemResource, error) {
	row := q.db.QueryRow(ctx, addProblemResource, arg.ProblemID, arg.Title, arg.Url)
	var i ProblemResource
	err := row.Scan(
		&i.ID,
		&i.ProblemID,
		&i.Title,
		&i.Url,
		&i.CreatedAt,
	)
	return i, err
}

const addTagToProblem = `-- name: AddTagToProblem :exec
INSERT INTO problem_tags (problem_id, tag_id)
VALUES ($1, $2)
ON CONFLICT DO NOTHING
`

type AddTagToProblemParams struct {
	ProblemID pgtype.UUID `db:"problem_id" json:"problem_id"`
	TagID     pgtype.UUID `db:"tag_id" json:"tag_id"`
}

func (q *Queries) AddTagToProblem(ctx context.Context, arg AddTagToProblemParams) error {
	_, err := q.db.Exec(ctx, addTagToProblem, arg.ProblemID, arg.TagID)
	return err
}

const archiveProblem = `-- name: ArchiveProblem :exec
UPDATE problems
SET archived_at = CURRENT_TIMESTAMP
WHERE id = $1
`

func (q *Queries) ArchiveProblem(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, archiveProblem, id)
	return err
}

const countAllProblems = `-- name: CountAllProblems :one
SELECT COUNT(*) FROM problems
WHERE archived_at IS NULL
`

func (q *Queries) CountAllProblems(ctx context.Context) (int64, error) {
	row := q.db.QueryRow(ctx, countAllProblems)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countTagUsage = `-- name: CountTagUsage :one
SELECT COUNT(*) FROM problem_tags
WHERE tag_id = $1
`

func (q *Queries) CountTagUsage(ctx context.Context, tagID pgtype.UUID) (int64, error) {
	row := q.db.QueryRow(ctx, countTagUsage, tagID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createProblem = `-- name: CreateProblem :one
INSERT INTO problems (
    organization_id, created_by, title, description, difficulty, external_link
) VALUES (
    $1, $2, $3, $4, $5, $6
)
RETURNING id, organization_id, created_by, title, description, difficulty, external_link, archived_at, created_at, updated_at
`

type CreateProblemParams struct {
	OrganizationID pgtype.UUID     `db:"organization_id" json:"organization_id"`
	CreatedBy      pgtype.UUID     `db:"created_by" json:"created_by"`
	Title          string          `db:"title" json:"title"`
	Description    pgtype.Text     `db:"description" json:"description"`
	Difficulty     DifficultyLevel `db:"difficulty" json:"difficulty"`
	ExternalLink   pgtype.Text     `db:"external_link" json:"external_link"`
}

func (q *Queries) CreateProblem(ctx context.Context, arg CreateProblemParams) (Problem, error) {
	row := q.db.QueryRow(ctx, createProblem,
		arg.OrganizationID,
		arg.CreatedBy,
		arg.Title,
		arg.Description,
		arg.Difficulty,
		arg.ExternalLink,
	)
	var i Problem
	err := row.Scan(
		&i.ID,
		&i.OrganizationID,
		&i.CreatedBy,
		&i.Title,
		&i.Description,
		&i.Difficulty,
		&i.ExternalLink,
		&i.ArchivedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createTag = `-- name: CreateTag :one

INSERT INTO tags (
    organization_id, created_by, name
) VALUES (
    $1, $2, $3
)
RETURNING id, organization_id, created_by, name, created_at
`

type CreateTagParams struct {
	OrganizationID pgtype.UUID `db:"organization_id" json:"organization_id"`
	CreatedBy      pgtype.UUID `db:"created_by" json:"created_by"`
	Name           string      `db:"name" json:"name"`
}

// Tags
func (q *Queries) CreateTag(ctx context.Context, arg CreateTagParams) (Tag, error) {
	row := q.db.QueryRow(ctx, createTag, arg.OrganizationID, arg.CreatedBy, arg.Name)
	var i Tag
	err := row.Scan(
		&i.ID,
		&i.OrganizationID,
		&i.CreatedBy,
		&i.Name,
		&i.CreatedAt,
	)
	return i, err
}

const deleteProblemResource = `-- name: DeleteProblemResource :exec
DELETE FROM problem_resources
WHERE id = $1
`

func (q *Queries) DeleteProblemResource(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, deleteProblemResource, id)
	return err
}

const deleteTag = `-- name: DeleteTag :exec
DELETE FROM tags
WHERE id = $1
`

func (q *Queries) DeleteTag(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, deleteTag, id)
	return err
}

const getProblem = `-- name: GetProblem :one
SELECT id, organization_id, created_by, title, description, difficulty, external_link, archived_at, created_at, updated_at FROM problems
WHERE id = $1 AND archived_at IS NULL LIMIT 1
`

func (q *Queries) GetProblem(ctx context.Context, id pgtype.UUID) (Problem, error) {
	row := q.db.QueryRow(ctx, getProblem, id)
	var i Problem
	err := row.Scan(
		&i.ID,
		&i.OrganizationID,
		&i.CreatedBy,
		&i.Title,
		&i.Description,
		&i.Difficulty,
		&i.ExternalLink,
		&i.ArchivedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getProblemResource = `-- name: GetProblemResource :one
SELECT id, problem_id, title, url, created_at FROM problem_resources
WHERE id = $1 LIMIT 1
`

func (q *Queries) GetProblemResource(ctx context.Context, id pgtype.UUID) (ProblemResource, error) {
	row := q.db.QueryRow(ctx, getProblemResource, id)
	var i ProblemResource
	err := row.Scan(
		&i.ID,
		&i.ProblemID,
		&i.Title,
		&i.Url,
		&i.CreatedAt,
	)
	return i, err
}

const getTag = `-- name: GetTag :one
SELECT id, organization_id, created_by, name, created_at FROM tags
WHERE id = $1 LIMIT 1
`

func (q *Queries) GetTag(ctx context.Context, id pgtype.UUID) (Tag, error) {
	row := q.db.QueryRow(ctx, getTag, id)
	var i Tag
	err := row.Scan(
		&i.ID,
		&i.OrganizationID,
		&i.CreatedBy,
		&i.Name,
		&i.CreatedAt,
	)
	return i, err
}

const getTagByName = `-- name: GetTagByName :one
SELECT id, organization_id, created_by, name, created_at FROM tags
WHERE organization_id = $1 AND name = $2 LIMIT 1
`

type GetTagByNameParams struct {
	OrganizationID pgtype.UUID `db:"organization_id" json:"organization_id"`
	Name           string      `db:"name" json:"name"`
}

func (q *Queries) GetTagByName(ctx context.Context, arg GetTagByNameParams) (Tag, error) {
	row := q.db.QueryRow(ctx, getTagByName, arg.OrganizationID, arg.Name)
	var i Tag
	err := row.Scan(
		&i.ID,
		&i.OrganizationID,
		&i.CreatedBy,
		&i.Name,
		&i.CreatedAt,
	)
	return i, err
}

const getTagsByIDs = `-- name: GetTagsByIDs :many
SELECT id, organization_id, created_by, name, created_at FROM tags
WHERE id = ANY($1::uuid[])
`

func (q *Queries) GetTagsByIDs(ctx context.Context, dollar_1 []pgtype.UUID) ([]Tag, error) {
	rows, err := q.db.Query(ctx, getTagsByIDs, dollar_1)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Tag{}
	for rows.Next() {
		var i Tag
		if err := rows.Scan(
			&i.ID,
			&i.OrganizationID,
			&i.CreatedBy,
			&i.Name,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listAllProblems = `-- name: ListAllProblems :many

SELECT p.id, p.organization_id, p.created_by, p.title, p.description, p.difficulty, p.external_link, p.archived_at, p.created_at, p.updated_at, o.name as organization_name, o.slug as organization_slug
FROM problems p
JOIN organizations o ON p.organization_id = o.id
WHERE p.archived_at IS NULL
ORDER BY p.created_at DESC
LIMIT $1 OFFSET $2
`

type ListAllProblemsParams struct {
	Limit  int32 `db:"limit" json:"limit"`
	Offset int32 `db:"offset" json:"offset"`
}

type ListAllProblemsRow struct {
	ID               pgtype.UUID        `db:"id" json:"id"`
	OrganizationID   pgtype.UUID        `db:"organization_id" json:"organization_id"`
	CreatedBy        pgtype.UUID        `db:"created_by" json:"created_by"`
	Title            string             `db:"title" json:"title"`
	Description      pgtype.Text        `db:"description" json:"description"`
	Difficulty       DifficultyLevel    `db:"difficulty" json:"difficulty"`
	ExternalLink     pgtype.Text        `db:"external_link" json:"external_link"`
	ArchivedAt       pgtype.Timestamptz `db:"archived_at" json:"archived_at"`
	CreatedAt        pgtype.Timestamptz `db:"created_at" json:"created_at"`
	UpdatedAt        pgtype.Timestamptz `db:"updated_at" json:"updated_at"`
	OrganizationName string             `db:"organization_name" json:"organization_name"`
	OrganizationSlug string             `db:"organization_slug" json:"organization_slug"`
}

// Super Admin Queries
func (q *Queries) ListAllProblems(ctx context.Context, arg ListAllProblemsParams) ([]ListAllProblemsRow, error) {
	rows, err := q.db.Query(ctx, listAllProblems, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListAllProblemsRow{}
	for rows.Next() {
		var i ListAllProblemsRow
		if err := rows.Scan(
			&i.ID,
			&i.OrganizationID,
			&i.CreatedBy,
			&i.Title,
			&i.Description,
			&i.Difficulty,
			&i.ExternalLink,
			&i.ArchivedAt,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.OrganizationName,
			&i.OrganizationSlug,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listProblemResources = `-- name: ListProblemResources :many
SELECT id, problem_id, title, url, created_at FROM problem_resources
WHERE problem_id = $1
ORDER BY created_at ASC
`

func (q *Queries) ListProblemResources(ctx context.Context, problemID pgtype.UUID) ([]ProblemResource, error) {
	rows, err := q.db.Query(ctx, listProblemResources, problemID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ProblemResource{}
	for rows.Next() {
		var i ProblemResource
		if err := rows.Scan(
			&i.ID,
			&i.ProblemID,
			&i.Title,
			&i.Url,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listProblemTags = `-- name: ListProblemTags :many
SELECT t.id, t.organization_id, t.created_by, t.name, t.created_at FROM tags t
JOIN problem_tags pt ON t.id = pt.tag_id
WHERE pt.problem_id = $1
`

func (q *Queries) ListProblemTags(ctx context.Context, problemID pgtype.UUID) ([]Tag, error) {
	rows, err := q.db.Query(ctx, listProblemTags, problemID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Tag{}
	for rows.Next() {
		var i Tag
		if err := rows.Scan(
			&i.ID,
			&i.OrganizationID,
			&i.CreatedBy,
			&i.Name,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listProblemsByOrg = `-- name: ListProblemsByOrg :many
SELECT id, organization_id, created_by, title, description, difficulty, external_link, archived_at, created_at, updated_at FROM problems
WHERE organization_id = $1 AND archived_at IS NULL
ORDER BY created_at DESC
`

func (q *Queries) ListProblemsByOrg(ctx context.Context, organizationID pgtype.UUID) ([]Problem, error) {
	rows, err := q.db.Query(ctx, listProblemsByOrg, organizationID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Problem{}
	for rows.Next() {
		var i Problem
		if err := rows.Scan(
			&i.ID,
			&i.OrganizationID,
			&i.CreatedBy,
			&i.Title,
			&i.Description,
			&i.Difficulty,
			&i.ExternalLink,
			&i.ArchivedAt,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTagsByOrg = `-- name: ListTagsByOrg :many
SELECT id, organization_id, created_by, name, created_at FROM tags
WHERE organization_id = $1
ORDER BY name ASC
`

func (q *Queries) ListTagsByOrg(ctx context.Context, organizationID pgtype.UUID) ([]Tag, error) {
	rows, err := q.db.Query(ctx, listTagsByOrg, organizationID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Tag{}
	for rows.Next() {
		var i Tag
		if err := rows.Scan(
			&i.ID,
			&i.OrganizationID,
			&i.CreatedBy,
			&i.Name,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const removeTagFromProblem = `-- name: RemoveTagFromProblem :exec
DELETE FROM problem_tags
WHERE problem_id = $1 AND tag_id = $2
`

type RemoveTagFromProblemParams struct {
	ProblemID pgtype.UUID `db:"problem_id" json:"problem_id"`
	TagID     pgtype.UUID `db:"tag_id" json:"tag_id"`
}

func (q *Queries) RemoveTagFromProblem(ctx context.Context, arg RemoveTagFromProblemParams) error {
	_, err := q.db.Exec(ctx, removeTagFromProblem, arg.ProblemID, arg.TagID)
	return err
}

const searchTagsByName = `-- name: SearchTagsByName :many
SELECT id, organization_id, created_by, name, created_at FROM tags
WHERE organization_id = $1 AND name ILIKE '%' || $2::text || '%'
ORDER BY name ASC
`

type SearchTagsByNameParams struct {
	OrganizationID pgtype.UUID `db:"organization_id" json:"organization_id"`
	Name           string      `db:"name" json:"name"`
}

func (q *Queries) SearchTagsByName(ctx context.Context, arg SearchTagsByNameParams) ([]Tag, error) {
	rows, err := q.db.Query(ctx, searchTagsByName, arg.OrganizationID, arg.Name)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Tag{}
	for rows.Next() {
		var i Tag
		if err := rows.Scan(
			&i.ID,
			&i.OrganizationID,
			&i.CreatedBy,
			&i.Name,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateProblem = `-- name: UpdateProblem :one
UPDATE problems
SET 
    title = COALESCE($2, title),
    description = COALESCE($3, description),
    difficulty = COALESCE($4, difficulty),
    external_link = COALESCE($5, external_link),
    updated_at = CURRENT_TIMESTAMP
WHERE id = $1
RETURNING id, organization_id, created_by, title, description, difficulty, external_link, archived_at, created_at, updated_at
`

type UpdateProblemParams struct {
	ID           pgtype.UUID         `db:"id" json:"id"`
	Title        pgtype.Text         `db:"title" json:"title"`
	Description  pgtype.Text         `db:"description" json:"description"`
	Difficulty   NullDifficultyLevel `db:"difficulty" json:"difficulty"`
	ExternalLink pgtype.Text         `db:"external_link" json:"external_link"`
}

func (q *Queries) UpdateProblem(ctx context.Context, arg UpdateProblemParams) (Problem, error) {
	row := q.db.QueryRow(ctx, updateProblem,
		arg.ID,
		arg.Title,
		arg.Description,
		arg.Difficulty,
		arg.ExternalLink,
	)
	var i Problem
	err := row.Scan(
		&i.ID,
		&i.OrganizationID,
		&i.CreatedBy,
		&i.Title,
		&i.Description,
		&i.Difficulty,
		&i.ExternalLink,
		&i.ArchivedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateProblemResource = `-- name: UpdateProblemResource :one
UPDATE problem_resources
SET 
    title = COALESCE($2, title),
    url = COALESCE($3, url)
WHERE id = $1
RETURNING id, problem_id, title, url, created_at
`

type UpdateProblemResourceParams struct {
	ID    pgtype.UUID `db:"id" json:"id"`
	Title pgtype.Text `db:"title" json:"title"`
	Url   pgtype.Text `db:"url" json:"url"`
}

func (q *Queries) UpdateProblemResource(ctx context.Context, arg UpdateProblemResourceParams) (ProblemResource, error) {
	row := q.db.QueryRow(ctx, updateProblemResource, arg.ID, arg.Title, arg.Url)
	var i ProblemResource
	err := row.Scan(
		&i.ID,
		&i.ProblemID,
		&i.Title,
		&i.Url,
		&i.CreatedAt,
	)
	return i, err
}

const updateTag = `-- name: UpdateTag :one
UPDATE tags
SET name = $2
WHERE id = $1
RETURNING id, organization_id, created_by, name, created_at
`

type UpdateTagParams struct {
	ID   pgtype.UUID `db:"id" json:"id"`
	Name string      `db:"name" json:"name"`
}

func (q *Queries) UpdateTag(ctx context.Context, arg UpdateTagParams) (Tag, error) {
	row := q.db.QueryRow(ctx, updateTag, arg.ID, arg.Name)
	var i Tag
	err := row.Scan(
		&i.ID,
		&i.OrganizationID,
		&i.CreatedBy,
		&i.Name,
		&i.CreatedAt,
	)
	return i, err
}

const countProblemAssignments = `-- name: CountProblemAssignments :one
SELECT COUNT(*) FROM assignment_group_problems
WHERE problem_id = $1
`

func (q *Queries) CountProblemAssignments(ctx context.Context, problemID pgtype.UUID) (int64, error) {
	row := q.db.QueryRow(ctx, countProblemAssignments, problemID)
	var count int64
	err := row.Scan(&count)
	return count, err
}
