// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: problem.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const addProblemResource = `-- name: AddProblemResource :one

INSERT INTO problem_resources (
    problem_id, title, url
) VALUES (
    $1, $2, $3
)
RETURNING id, problem_id, title, url, created_at
`

type AddProblemResourceParams struct {
	ProblemID pgtype.UUID `db:"problem_id" json:"problem_id"`
	Title     pgtype.Text `db:"title" json:"title"`
	Url       pgtype.Text `db:"url" json:"url"`
}

// Resources
func (q *Queries) AddProblemResource(ctx context.Context, arg AddProblemResourceParams) (ProblemResource, error) {
	row := q.db.QueryRow(ctx, addProblemResource, arg.ProblemID, arg.Title, arg.Url)
	var i ProblemResource
	err := row.Scan(
		&i.ID,
		&i.ProblemID,
		&i.Title,
		&i.Url,
		&i.CreatedAt,
	)
	return i, err
}

const addTagToProblem = `-- name: AddTagToProblem :exec
INSERT INTO problem_tags (problem_id, tag_id)
VALUES ($1, $2)
ON CONFLICT DO NOTHING
`

type AddTagToProblemParams struct {
	ProblemID pgtype.UUID `db:"problem_id" json:"problem_id"`
	TagID     pgtype.UUID `db:"tag_id" json:"tag_id"`
}

func (q *Queries) AddTagToProblem(ctx context.Context, arg AddTagToProblemParams) error {
	_, err := q.db.Exec(ctx, addTagToProblem, arg.ProblemID, arg.TagID)
	return err
}

const archiveProblem = `-- name: ArchiveProblem :exec
UPDATE problems
SET archived_at = CURRENT_TIMESTAMP
WHERE id = $1
`

func (q *Queries) ArchiveProblem(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, archiveProblem, id)
	return err
}

const createProblem = `-- name: CreateProblem :one
INSERT INTO problems (
    organization_id, created_by, title, description, difficulty, external_link
) VALUES (
    $1, $2, $3, $4, $5, $6
)
RETURNING id, organization_id, created_by, title, description, difficulty, external_link, archived_at, created_at, updated_at
`

type CreateProblemParams struct {
	OrganizationID pgtype.UUID     `db:"organization_id" json:"organization_id"`
	CreatedBy      pgtype.UUID     `db:"created_by" json:"created_by"`
	Title          string          `db:"title" json:"title"`
	Description    pgtype.Text     `db:"description" json:"description"`
	Difficulty     DifficultyLevel `db:"difficulty" json:"difficulty"`
	ExternalLink   pgtype.Text     `db:"external_link" json:"external_link"`
}

func (q *Queries) CreateProblem(ctx context.Context, arg CreateProblemParams) (Problem, error) {
	row := q.db.QueryRow(ctx, createProblem,
		arg.OrganizationID,
		arg.CreatedBy,
		arg.Title,
		arg.Description,
		arg.Difficulty,
		arg.ExternalLink,
	)
	var i Problem
	err := row.Scan(
		&i.ID,
		&i.OrganizationID,
		&i.CreatedBy,
		&i.Title,
		&i.Description,
		&i.Difficulty,
		&i.ExternalLink,
		&i.ArchivedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createTag = `-- name: CreateTag :one

INSERT INTO tags (
    organization_id, created_by, name
) VALUES (
    $1, $2, $3
)
ON CONFLICT (organization_id, name) DO UPDATE SET name = EXCLUDED.name
RETURNING id, organization_id, created_by, name, created_at
`

type CreateTagParams struct {
	OrganizationID pgtype.UUID `db:"organization_id" json:"organization_id"`
	CreatedBy      pgtype.UUID `db:"created_by" json:"created_by"`
	Name           string      `db:"name" json:"name"`
}

// Tags
func (q *Queries) CreateTag(ctx context.Context, arg CreateTagParams) (Tag, error) {
	row := q.db.QueryRow(ctx, createTag, arg.OrganizationID, arg.CreatedBy, arg.Name)
	var i Tag
	err := row.Scan(
		&i.ID,
		&i.OrganizationID,
		&i.CreatedBy,
		&i.Name,
		&i.CreatedAt,
	)
	return i, err
}

const deleteProblemResource = `-- name: DeleteProblemResource :exec
DELETE FROM problem_resources
WHERE id = $1
`

func (q *Queries) DeleteProblemResource(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, deleteProblemResource, id)
	return err
}

const getProblem = `-- name: GetProblem :one
SELECT id, organization_id, created_by, title, description, difficulty, external_link, archived_at, created_at, updated_at FROM problems
WHERE id = $1 AND archived_at IS NULL LIMIT 1
`

func (q *Queries) GetProblem(ctx context.Context, id pgtype.UUID) (Problem, error) {
	row := q.db.QueryRow(ctx, getProblem, id)
	var i Problem
	err := row.Scan(
		&i.ID,
		&i.OrganizationID,
		&i.CreatedBy,
		&i.Title,
		&i.Description,
		&i.Difficulty,
		&i.ExternalLink,
		&i.ArchivedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listProblemResources = `-- name: ListProblemResources :many
SELECT id, problem_id, title, url, created_at FROM problem_resources
WHERE problem_id = $1
ORDER BY created_at ASC
`

func (q *Queries) ListProblemResources(ctx context.Context, problemID pgtype.UUID) ([]ProblemResource, error) {
	rows, err := q.db.Query(ctx, listProblemResources, problemID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ProblemResource{}
	for rows.Next() {
		var i ProblemResource
		if err := rows.Scan(
			&i.ID,
			&i.ProblemID,
			&i.Title,
			&i.Url,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listProblemTags = `-- name: ListProblemTags :many
SELECT t.id, t.organization_id, t.created_by, t.name, t.created_at FROM tags t
JOIN problem_tags pt ON t.id = pt.tag_id
WHERE pt.problem_id = $1
`

func (q *Queries) ListProblemTags(ctx context.Context, problemID pgtype.UUID) ([]Tag, error) {
	rows, err := q.db.Query(ctx, listProblemTags, problemID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Tag{}
	for rows.Next() {
		var i Tag
		if err := rows.Scan(
			&i.ID,
			&i.OrganizationID,
			&i.CreatedBy,
			&i.Name,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listProblemsByOrg = `-- name: ListProblemsByOrg :many
SELECT id, organization_id, created_by, title, description, difficulty, external_link, archived_at, created_at, updated_at FROM problems
WHERE organization_id = $1 AND archived_at IS NULL
ORDER BY created_at DESC
`

func (q *Queries) ListProblemsByOrg(ctx context.Context, organizationID pgtype.UUID) ([]Problem, error) {
	rows, err := q.db.Query(ctx, listProblemsByOrg, organizationID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Problem{}
	for rows.Next() {
		var i Problem
		if err := rows.Scan(
			&i.ID,
			&i.OrganizationID,
			&i.CreatedBy,
			&i.Title,
			&i.Description,
			&i.Difficulty,
			&i.ExternalLink,
			&i.ArchivedAt,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTagsByOrg = `-- name: ListTagsByOrg :many
SELECT id, organization_id, created_by, name, created_at FROM tags
WHERE organization_id = $1
ORDER BY name ASC
`

func (q *Queries) ListTagsByOrg(ctx context.Context, organizationID pgtype.UUID) ([]Tag, error) {
	rows, err := q.db.Query(ctx, listTagsByOrg, organizationID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Tag{}
	for rows.Next() {
		var i Tag
		if err := rows.Scan(
			&i.ID,
			&i.OrganizationID,
			&i.CreatedBy,
			&i.Name,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const removeTagFromProblem = `-- name: RemoveTagFromProblem :exec
DELETE FROM problem_tags
WHERE problem_id = $1 AND tag_id = $2
`

type RemoveTagFromProblemParams struct {
	ProblemID pgtype.UUID `db:"problem_id" json:"problem_id"`
	TagID     pgtype.UUID `db:"tag_id" json:"tag_id"`
}

func (q *Queries) RemoveTagFromProblem(ctx context.Context, arg RemoveTagFromProblemParams) error {
	_, err := q.db.Exec(ctx, removeTagFromProblem, arg.ProblemID, arg.TagID)
	return err
}

const updateProblem = `-- name: UpdateProblem :one
UPDATE problems
SET 
    title = COALESCE($2, title),
    description = COALESCE($3, description),
    difficulty = COALESCE($4, difficulty),
    external_link = COALESCE($5, external_link),
    updated_at = CURRENT_TIMESTAMP
WHERE id = $1
RETURNING id, organization_id, created_by, title, description, difficulty, external_link, archived_at, created_at, updated_at
`

type UpdateProblemParams struct {
	ID           pgtype.UUID         `db:"id" json:"id"`
	Title        pgtype.Text         `db:"title" json:"title"`
	Description  pgtype.Text         `db:"description" json:"description"`
	Difficulty   NullDifficultyLevel `db:"difficulty" json:"difficulty"`
	ExternalLink pgtype.Text         `db:"external_link" json:"external_link"`
}

func (q *Queries) UpdateProblem(ctx context.Context, arg UpdateProblemParams) (Problem, error) {
	row := q.db.QueryRow(ctx, updateProblem,
		arg.ID,
		arg.Title,
		arg.Description,
		arg.Difficulty,
		arg.ExternalLink,
	)
	var i Problem
	err := row.Scan(
		&i.ID,
		&i.OrganizationID,
		&i.CreatedBy,
		&i.Title,
		&i.Description,
		&i.Difficulty,
		&i.ExternalLink,
		&i.ArchivedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
