// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: web_ui.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const webGetLeaderboard = `-- name: WebGetLeaderboard :many
SELECT 
    u.id,
    u.name as first_name,
    '' as last_name,
    le.problems_completed as solved
FROM leaderboard_entries le
JOIN bootcamp_enrollments be ON le.bootcamp_enrollment_id = be.id
JOIN organization_members om ON be.organization_member_id = om.id
JOIN users u ON om.user_id = u.id
ORDER BY le.problems_completed DESC, le.calculated_at DESC
LIMIT 100
`

type WebGetLeaderboardRow struct {
	ID        pgtype.UUID `db:"id" json:"id"`
	FirstName string      `db:"first_name" json:"first_name"`
	LastName  string      `db:"last_name" json:"last_name"`
	Solved    int32       `db:"solved" json:"solved"`
}

func (q *Queries) WebGetLeaderboard(ctx context.Context) ([]WebGetLeaderboardRow, error) {
	rows, err := q.db.Query(ctx, webGetLeaderboard)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []WebGetLeaderboardRow{}
	for rows.Next() {
		var i WebGetLeaderboardRow
		if err := rows.Scan(
			&i.ID,
			&i.FirstName,
			&i.LastName,
			&i.Solved,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const webGetMenteeQuestion = `-- name: WebGetMenteeQuestion :one
SELECT 
    ap.problem_id as id,
    p.title,
    p.description,
    p.difficulty,
    a.status as assignment_status,
    ap.status as progress_status,
    a.assigned_at,
    ap.completed_at,
    ap.solution_link as solution_url,
    ap.notes as solution
FROM assignment_problems ap
JOIN problems p ON ap.problem_id = p.id
JOIN assignments a ON ap.assignment_id = a.id
JOIN bootcamp_enrollments be ON a.bootcamp_enrollment_id = be.id
JOIN organization_members om ON be.organization_member_id = om.id
WHERE om.user_id = $1 AND p.id = $2
LIMIT 1
`

type WebGetMenteeQuestionParams struct {
	UserID pgtype.UUID `db:"user_id" json:"user_id"`
	ID     pgtype.UUID `db:"id" json:"id"`
}

type WebGetMenteeQuestionRow struct {
	ID               pgtype.UUID             `db:"id" json:"id"`
	Title            string                  `db:"title" json:"title"`
	Description      pgtype.Text             `db:"description" json:"description"`
	Difficulty       DifficultyLevel         `db:"difficulty" json:"difficulty"`
	AssignmentStatus AssignmentStatus        `db:"assignment_status" json:"assignment_status"`
	ProgressStatus   AssignmentProblemStatus `db:"progress_status" json:"progress_status"`
	AssignedAt       pgtype.Timestamptz      `db:"assigned_at" json:"assigned_at"`
	CompletedAt      pgtype.Timestamptz      `db:"completed_at" json:"completed_at"`
	SolutionUrl      pgtype.Text             `db:"solution_url" json:"solution_url"`
	Solution         pgtype.Text             `db:"solution" json:"solution"`
}

func (q *Queries) WebGetMenteeQuestion(ctx context.Context, arg WebGetMenteeQuestionParams) (WebGetMenteeQuestionRow, error) {
	row := q.db.QueryRow(ctx, webGetMenteeQuestion, arg.UserID, arg.ID)
	var i WebGetMenteeQuestionRow
	err := row.Scan(
		&i.ID,
		&i.Title,
		&i.Description,
		&i.Difficulty,
		&i.AssignmentStatus,
		&i.ProgressStatus,
		&i.AssignedAt,
		&i.CompletedAt,
		&i.SolutionUrl,
		&i.Solution,
	)
	return i, err
}

const webGetProfileStats = `-- name: WebGetProfileStats :one
SELECT 
    u.name as first_name,
    u.email,
    u.created_at as joined_at,
    COALESCE(le.problems_completed, 0) as solved
FROM users u
LEFT JOIN organization_members om ON om.user_id = u.id
LEFT JOIN bootcamp_enrollments be ON be.organization_member_id = om.id AND be.status = 'active'
LEFT JOIN leaderboard_entries le ON le.bootcamp_enrollment_id = be.id
WHERE u.id = $1
LIMIT 1
`

type WebGetProfileStatsRow struct {
	FirstName string             `db:"first_name" json:"first_name"`
	Email     pgtype.Text        `db:"email" json:"email"`
	JoinedAt  pgtype.Timestamptz `db:"joined_at" json:"joined_at"`
	Solved    int32              `db:"solved" json:"solved"`
}

func (q *Queries) WebGetProfileStats(ctx context.Context, id pgtype.UUID) (WebGetProfileStatsRow, error) {
	row := q.db.QueryRow(ctx, webGetProfileStats, id)
	var i WebGetProfileStatsRow
	err := row.Scan(
		&i.FirstName,
		&i.Email,
		&i.JoinedAt,
		&i.Solved,
	)
	return i, err
}

const webListMenteeQuestions = `-- name: WebListMenteeQuestions :many
SELECT 
    ap.problem_id as id,
    p.title,
    p.description,
    p.difficulty,
    a.status as assignment_status,
    ap.status as progress_status,
    a.assigned_at,
    ap.completed_at,
    ap.solution_link as solution_url,
    ap.notes as solution,
    '' as resources
FROM assignment_problems ap
JOIN problems p ON ap.problem_id = p.id
JOIN assignments a ON ap.assignment_id = a.id
JOIN bootcamp_enrollments be ON a.bootcamp_enrollment_id = be.id
JOIN organization_members om ON be.organization_member_id = om.id
WHERE om.user_id = $1
ORDER BY ap.created_at DESC
`

type WebListMenteeQuestionsRow struct {
	ID               pgtype.UUID             `db:"id" json:"id"`
	Title            string                  `db:"title" json:"title"`
	Description      pgtype.Text             `db:"description" json:"description"`
	Difficulty       DifficultyLevel         `db:"difficulty" json:"difficulty"`
	AssignmentStatus AssignmentStatus        `db:"assignment_status" json:"assignment_status"`
	ProgressStatus   AssignmentProblemStatus `db:"progress_status" json:"progress_status"`
	AssignedAt       pgtype.Timestamptz      `db:"assigned_at" json:"assigned_at"`
	CompletedAt      pgtype.Timestamptz      `db:"completed_at" json:"completed_at"`
	SolutionUrl      pgtype.Text             `db:"solution_url" json:"solution_url"`
	Solution         pgtype.Text             `db:"solution" json:"solution"`
	Resources        string                  `db:"resources" json:"resources"`
}

func (q *Queries) WebListMenteeQuestions(ctx context.Context, userID pgtype.UUID) ([]WebListMenteeQuestionsRow, error) {
	rows, err := q.db.Query(ctx, webListMenteeQuestions, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []WebListMenteeQuestionsRow{}
	for rows.Next() {
		var i WebListMenteeQuestionsRow
		if err := rows.Scan(
			&i.ID,
			&i.Title,
			&i.Description,
			&i.Difficulty,
			&i.AssignmentStatus,
			&i.ProgressStatus,
			&i.AssignedAt,
			&i.CompletedAt,
			&i.SolutionUrl,
			&i.Solution,
			&i.Resources,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const webListPendingRequests = `-- name: WebListPendingRequests :many

SELECT be.id, u.id as user_id, u.name as first_name, u.email, be.enrolled_at as signed_up_at, be.status
FROM bootcamp_enrollments be
JOIN organization_members om ON be.organization_member_id = om.id
JOIN users u ON om.user_id = u.id
WHERE be.status = 'pending'
ORDER BY be.enrolled_at DESC
`

type WebListPendingRequestsRow struct {
	ID         pgtype.UUID        `db:"id" json:"id"`
	UserID     pgtype.UUID        `db:"user_id" json:"user_id"`
	FirstName  string             `db:"first_name" json:"first_name"`
	Email      pgtype.Text        `db:"email" json:"email"`
	SignedUpAt pgtype.Timestamptz `db:"signed_up_at" json:"signed_up_at"`
	Status     EnrollmentStatus   `db:"status" json:"status"`
}

// Web UI Specific Queries for Coderz Dashboard
func (q *Queries) WebListPendingRequests(ctx context.Context) ([]WebListPendingRequestsRow, error) {
	rows, err := q.db.Query(ctx, webListPendingRequests)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []WebListPendingRequestsRow{}
	for rows.Next() {
		var i WebListPendingRequestsRow
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.FirstName,
			&i.Email,
			&i.SignedUpAt,
			&i.Status,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const webUpdateQuestionDetails = `-- name: WebUpdateQuestionDetails :exec
UPDATE assignment_problems
SET notes = COALESCE($3, notes),
    solution_link = COALESCE($4, solution_link),
    updated_at = CURRENT_TIMESTAMP
FROM assignments a
JOIN bootcamp_enrollments be ON a.bootcamp_enrollment_id = be.id
JOIN organization_members om ON be.organization_member_id = om.id
WHERE assignment_problems.assignment_id = a.id 
  AND om.user_id = $1 
  AND assignment_problems.problem_id = $2
`

type WebUpdateQuestionDetailsParams struct {
	UserID       pgtype.UUID `db:"user_id" json:"user_id"`
	ProblemID    pgtype.UUID `db:"problem_id" json:"problem_id"`
	Notes        pgtype.Text `db:"notes" json:"notes"`
	SolutionLink pgtype.Text `db:"solution_link" json:"solution_link"`
}

func (q *Queries) WebUpdateQuestionDetails(ctx context.Context, arg WebUpdateQuestionDetailsParams) error {
	_, err := q.db.Exec(ctx, webUpdateQuestionDetails,
		arg.UserID,
		arg.ProblemID,
		arg.Notes,
		arg.SolutionLink,
	)
	return err
}

const webUpdateQuestionProgress = `-- name: WebUpdateQuestionProgress :exec
UPDATE assignment_problems
SET status = $3, updated_at = CURRENT_TIMESTAMP,
    completed_at = CASE WHEN $3 = 'completed' THEN CURRENT_TIMESTAMP ELSE completed_at END
FROM assignments a
JOIN bootcamp_enrollments be ON a.bootcamp_enrollment_id = be.id
JOIN organization_members om ON be.organization_member_id = om.id
WHERE assignment_problems.assignment_id = a.id 
  AND om.user_id = $1 
  AND assignment_problems.problem_id = $2
`

type WebUpdateQuestionProgressParams struct {
	UserID    pgtype.UUID             `db:"user_id" json:"user_id"`
	ProblemID pgtype.UUID             `db:"problem_id" json:"problem_id"`
	Status    AssignmentProblemStatus `db:"status" json:"status"`
}

func (q *Queries) WebUpdateQuestionProgress(ctx context.Context, arg WebUpdateQuestionProgressParams) error {
	_, err := q.db.Exec(ctx, webUpdateQuestionProgress, arg.UserID, arg.ProblemID, arg.Status)
	return err
}
